import type { Flashcard } from "../types";

/**
 * 전기설비 확장 카드. topic은 chapters.ts CHAPTERS.전기설비 의 8챕터 중 하나:
 * 전선·케이블 / 배선재료·공구 / 배선공사 / 옥내배선 / 접지 / 피뢰·보호 /
 * 차단기·보호장치 / 변전·배전.  id 접두사: f-
 */
export const facilityCards: Flashcard[] = [
  // ───────────────────────── 전선·케이블 ─────────────────────────
  {
    id: "f-cable-iv-hiv",
    front: "절연전선 IV·HIV·OW·DV의 의미?",
    back: "IV: 600V 비닐 절연전선 (옥내, 최고허용온도 60℃)\nHIV: 600V 2종 비닐 절연전선 (내열, 75℃)\nOW: 옥외용 비닐 절연전선 (가공인입)\nDV: 인입용 비닐 절연전선 (가공 인입선)",
    subject: "전기설비",
    topic: "전선·케이블",
    source: "preset",
    hint: "I=옥내, O=옥외, D=인입(Drop)",
  },
  {
    id: "f-cable-sqmm-series",
    front: "전선 공칭단면적 표준 규격 수열?",
    back: "$1.5,\\ 2.5,\\ 4,\\ 6,\\ 10,\\ 16,\\ 25,\\ 35,\\ 50,\\ 70,\\ 95,\\ 120\\ \\text{mm}^2 \\cdots$\n주택 전등·콘센트는 보통 1.5~2.5 mm² 사용.\n단위는 mm²(스퀘어, SQ).",
    subject: "전기설비",
    topic: "전선·케이블",
    source: "preset",
    hint: "1.5부터 약 1.5~2배씩",
  },
  {
    id: "f-cable-ampacity-temp",
    front: "전선 허용전류에 영향을 주는 요인?",
    back: "1. 도체 단면적(클수록 ↑)\n2. 주위 온도(높을수록 ↓ — 보정계수 적용)\n3. 포설 방식(공중·매설·관내)\n4. 다회로 집합 시 전류감소계수\n허용전류는 절연물 최고허용온도로 결정.",
    subject: "전기설비",
    topic: "전선·케이블",
    source: "preset",
    hint: "온도↑·집합↑ → 허용전류↓",
  },
  {
    id: "f-cable-resistance-formula",
    front: "도체의 저항을 구하는 식?",
    back: "$R = \\rho \\cdot \\dfrac{L}{A}$\n$\\rho$ 고유저항[Ω·m], $L$ 길이[m], $A$ 단면적[m²].\n길이에 비례, 단면적에 반비례.\n구리 $\\rho \\approx 1.72 \\times 10^{-8}\\ \\Omega\\cdot\\text{m}$.",
    subject: "전기설비",
    topic: "전선·케이블",
    source: "preset",
    example: {
      question:
        "고유저항 $\\rho = 1.72 \\times 10^{-8}\\ \\Omega\\cdot\\text{m}$, 길이 100 m, 단면적 $4\\ \\text{mm}^2$ 구리선의 저항은?",
      solution: [
        "$A = 4\\ \\text{mm}^2 = 4 \\times 10^{-6}\\ \\text{m}^2$",
        "$R = \\rho \\dfrac{L}{A} = 1.72 \\times 10^{-8} \\times \\dfrac{100}{4 \\times 10^{-6}}$",
        "$R = 1.72 \\times 10^{-8} \\times 2.5 \\times 10^{7}$",
        "$R \\approx 0.43\\ \\Omega$",
      ],
      answer: "$R \\approx 0.43\\ \\Omega$",
    },
  },
  {
    id: "f-cable-voltage-drop",
    front: "단상 2선식 전압강하 약산식?",
    back: "$e = \\dfrac{35.6 \\cdot L \\cdot I}{1000 \\cdot A}$ [V]\n$L$ 전선길이[m], $I$ 전류[A], $A$ 단면적[mm²].\n3상 3선식은 계수 30.8 사용.",
    subject: "전기설비",
    topic: "전선·케이블",
    source: "preset",
    hint: "단상2선 35.6 / 3상3선 30.8",
    example: {
      question:
        "단상 2선식, 길이 50 m, 전류 20 A, 단면적 6 mm²일 때 전압강하는?",
      solution: [
        "$e = \\dfrac{35.6 \\times L \\times I}{1000 \\times A}$",
        "$e = \\dfrac{35.6 \\times 50 \\times 20}{1000 \\times 6}$",
        "$e = \\dfrac{35600}{6000} \\approx 5.93\\ \\text{V}$",
      ],
      answer: "$e \\approx 5.93\\ \\text{V}$",
    },
  },
  {
    id: "f-cable-cv-ct",
    front: "케이블 종류 CV·VV·CVV·FR-CV?",
    back: "CV: 가교폴리에틸렌 절연 비닐시스 (XLPE, 90℃, 전력)\nVV: 비닐 절연 비닐시스 (저압 전력)\nCVV: 제어용 비닐 케이블 (제어회로)\nFR-CV: 난연성 CV 케이블 (방재)",
    subject: "전기설비",
    topic: "전선·케이블",
    source: "preset",
    hint: "C=가교PE, V=비닐, FR=난연",
  },
  {
    id: "f-cable-stranded",
    front: "단선과 연선의 차이?",
    back: "단선: 1가닥 도체. 가공·고정 배선에 유리, 굵으면 시공 어려움.\n연선: 여러 소선을 꼰 도체. 유연해 굴곡 배선·이동용에 유리.\n연선 단면적 $= $ 소선 단면적 $\\times$ 소선 수.",
    subject: "전기설비",
    topic: "전선·케이블",
    source: "preset",
    example: {
      question: "소선 직경 1.6 mm 소선 7가닥 연선의 총 단면적은? (소선 1가닥 약 2.0 mm²)",
      solution: [
        "소선 1가닥 단면적 $\\approx \\dfrac{\\pi}{4} \\times 1.6^2 \\approx 2.0\\ \\text{mm}^2$",
        "연선 단면적 $= 2.0 \\times 7 = 14\\ \\text{mm}^2$",
      ],
      answer: "약 14 mm²",
    },
  },
  {
    id: "f-cable-acsr",
    front: "ACSR(강심 알루미늄 연선)이란?",
    back: "중심에 강선(인장강도 담당) + 바깥에 알루미늄선(도전 담당).\n경동선보다 가볍고 인장강도 큼 → 장경간 가공 송전선로에 사용.\n도전율은 구리보다 낮지만 경제적.",
    subject: "전기설비",
    topic: "전선·케이블",
    source: "preset",
    hint: "강심=강도, Al=도전",
  },
  {
    id: "f-cable-allowable-table",
    front: "절연전선(IV) 단면적별 대략 허용전류(기중, 참고값)?",
    back: "2.5 mm² ≈ 27 A\n4 mm² ≈ 35 A\n6 mm² ≈ 48 A\n10 mm² ≈ 66 A\n※ 포설조건·온도보정으로 변동(KEC 부속서 기준 적용).",
    subject: "전기설비",
    topic: "전선·케이블",
    source: "preset",
    hint: "수치는 조건별 변동 — 경향 암기",
  },
  {
    id: "f-cable-skin-effect",
    front: "표피효과(Skin Effect)란?",
    back: "교류에서 주파수가 높을수록 전류가 도체 표면에 집중되는 현상.\n→ 실효 단면적 감소 → 실효 저항 증가.\n주파수·도체 굵기·도전율·투자율이 클수록 표피효과 심해짐.",
    subject: "전기설비",
    topic: "전선·케이블",
    source: "preset",
    hint: "주파수↑ → 표면 집중",
  },
  {
    id: "f-cable-nominal-voltage",
    front: "저압·고압·특고압 구분 (KEC, 교류 기준)?",
    back: "저압: 교류 1 kV 이하 (직류 1.5 kV 이하)\n고압: 저압 초과 ~ 7 kV 이하\n특고압: 7 kV 초과\n※ KEC에서 종전 600 V/750 V 기준이 1 kV/1.5 kV로 개정됨.",
    subject: "전기설비",
    topic: "전선·케이블",
    source: "preset",
    hint: "KEC 개정값 — 저압 1 kV 이하",
  },
  {
    id: "f-cable-bundle-derating",
    front: "전선관 수용 가닥 수와 전류감소계수?",
    back: "한 관·트레이에 여러 회로를 모으면 방열이 나빠져 허용전류 감소.\n가닥(회로) 수가 많을수록 전류감소계수 작아짐(예: 3가닥 0.7대, 4~6가닥 0.6대 등 KEC 표 적용).\n관내 전선 총단면적은 관 내단면적의 약 32~48% 이하.",
    subject: "전기설비",
    topic: "전선·케이블",
    source: "preset",
    hint: "가닥↑ → 감소계수↓",
  },

  // ───────────────────────── 배선재료·공구 ─────────────────────────
  {
    id: "f-tool-megger",
    front: "절연저항계(메거)의 용도와 특징?",
    back: "절연저항(MΩ) 측정 전용. 내부에서 DC 고전압(250/500/1000 V)을 발생시켜 누설전류로 절연 상태 판정.\n측정 전 반드시 무전압(정전) 확인.\n절연저항이 클수록 양호.",
    subject: "전기설비",
    topic: "배선재료·공구",
    source: "preset",
    hint: "DC 고압 인가 → 절연 판정",
  },
  {
    id: "f-tool-earth-tester",
    front: "접지저항계 측정 방식?",
    back: "전위강하법(3극법): 접지전극 E, 보조전극 P·C를 일직선 배치.\nE-C 사이에 전류를 흘리고 E-P 전위차로 접지저항 산출.\nP는 보통 E-C 거리의 약 61.8% 지점.",
    subject: "전기설비",
    topic: "배선재료·공구",
    source: "preset",
    hint: "전위강하 3극법",
  },
  {
    id: "f-tool-clamp-meter",
    front: "후크온(클램프) 미터의 원리?",
    back: "도체를 자르지 않고 집게(CT)로 감싸 자기장으로 전류 측정.\n활선 상태에서 부하전류 측정 가능.\n누설전류 측정용은 왕복 전선을 함께 물려 차전류 검출.",
    subject: "전기설비",
    topic: "배선재료·공구",
    source: "preset",
    hint: "CT 원리 — 자르지 않고 측정",
  },
  {
    id: "f-tool-knockout",
    front: "녹아웃 펀치(노크아웃)의 용도?",
    back: "분전반·박스 철판에 전선관 접속용 둥근 구멍을 뚫는 공구.\n유압식·기계식이 있으며 규격 다이로 정확한 원형 가공.\n드릴 대비 변형 적고 깔끔.",
    subject: "전기설비",
    topic: "배선재료·공구",
    source: "preset",
  },
  {
    id: "f-tool-fish-tape",
    front: "철망(피시테이프)·통선의 용도?",
    back: "전선관 내부에 전선을 입선(insertion)할 때 먼저 관을 통과시켜 전선을 끌어당기는 안내선.\n강선·평강·플라스틱제. 윤활제(입선유)와 함께 사용해 마찰 감소.",
    subject: "전기설비",
    topic: "배선재료·공구",
    source: "preset",
    hint: "관에 전선 입선용 안내선",
  },
  {
    id: "f-tool-connector",
    front: "전선 접속재료 — 와이어커넥터·슬리브·압착단자?",
    back: "와이어커넥터(링형): 소선 비틀어 접속 후 캡 체결\n압착 슬리브: 전용 펜치로 압착(P·B형)\n압착단자(터미널): 기기 단자 접속용 (O형·Y형)\n접속점 전기저항·기계강도 확보가 핵심.",
    subject: "전기설비",
    topic: "배선재료·공구",
    source: "preset",
  },
  {
    id: "f-tool-conduit-bender",
    front: "히키(파이프 벤더)의 용도?",
    back: "금속전선관(박강·후강)을 원하는 각도로 구부리는 공구.\n관 찌그러짐 없이 일정 곡률 형성.\n금속관 곡률반지름은 관 안지름의 6배 이상 권장.",
    subject: "전기설비",
    topic: "배선재료·공구",
    source: "preset",
    hint: "곡률반지름 ≥ 안지름 6배",
  },
  {
    id: "f-tool-insulation-tape",
    front: "절연 테이프 종류와 용도?",
    back: "비닐 절연테이프: 일반 절연·식별\n자기융착 테이프: 늘려 감으면 자체 융착해 방수·절연 (옥외 접속)\n면테이프: 보호·고정\n접속부는 원래 절연 이상 두께로 감기.",
    subject: "전기설비",
    topic: "배선재료·공구",
    source: "preset",
  },
  {
    id: "f-tool-switch-types",
    front: "옥내 스위치(점멸기) 종류?",
    back: "단로(편극) 스위치: 1개소 점멸\n3로 스위치: 2개소에서 점멸 (계단·복도)\n4로 스위치: 3로와 조합해 3개소 이상 점멸\n자동·센서·조광(디머) 스위치 등.",
    subject: "전기설비",
    topic: "배선재료·공구",
    source: "preset",
    hint: "2개소=3로, 3개소=3로+4로",
  },
  {
    id: "f-tool-outlet-rating",
    front: "콘센트·플러그 정격 표시?",
    back: "정격전압·정격전류로 표시 (예: 250 V 15 A, 250 V 16 A).\n접지극 있는 콘센트는 접지선(PE) 결선 필수.\n방수형(IP등급)은 옥외·습기 장소용.",
    subject: "전기설비",
    topic: "배선재료·공구",
    source: "preset",
  },
  {
    id: "f-tool-conduit-accessory",
    front: "금속관 공사 부속재료?",
    back: "커플링: 관과 관 연결\n로크너트·부싱: 박스 고정 및 전선 보호\n노멀밴드: 관 직각 굴곡\n엔트런스 캡: 옥외 인입 빗물 침입 방지\n새들·행거: 관 지지·고정",
    subject: "전기설비",
    topic: "배선재료·공구",
    source: "preset",
    hint: "부싱=전선보호, 새들=지지",
  },
  {
    id: "f-tool-pliers",
    front: "펜치·플라이어·롱노즈의 차이?",
    back: "펜치: 전선 절단·구부림·잡기 (만능)\n롱노즈(라디오뺀치): 좁은 곳 작업·고리 만들기\n워터펌프플라이어: 큰 너트·관 물기\n바이스플라이어(그립): 고정 후 강력 파지",
    subject: "전기설비",
    topic: "배선재료·공구",
    source: "preset",
  },
  {
    id: "f-tool-test-lamp",
    front: "회로시험기(테스터)·검상기 용도?",
    back: "멀티미터: 전압·전류·저항·도통 측정\n검상기(상회전계): 3상 전원의 상회전 방향(정·역상) 확인\n도통시험: 전원을 끈 상태에서 단선·단락 확인.",
    subject: "전기설비",
    topic: "배선재료·공구",
    source: "preset",
    hint: "검상기 = 3상 상회전 확인",
  },

  // ───────────────────────── 배선공사 ─────────────────────────
  {
    id: "f-work-conduit-fill",
    front: "금속관 공사 시 전선 점유율 기준?",
    back: "관 내 전선 절연물 포함 총단면적은 관 내 단면적의 일정 비율 이하.\n동일 굵기 전선: 관 단면적의 약 48% 이하.\n다른 굵기 혼합: 약 32% 이하.\n과밀하면 입선 곤란·방열 불량.",
    subject: "전기설비",
    topic: "배선공사",
    source: "preset",
    hint: "동일굵기 48%, 혼합 32%",
  },
  {
    id: "f-work-metal-conduit-thick",
    front: "후강전선관과 박강전선관 호칭?",
    back: "후강전선관: 안지름 기준 짝수 호칭 (16,22,28,36,42,54,70,82,92,104 mm)\n박강전선관: 바깥지름 기준 홀수(근사) 호칭 (19,25,31,39,51,63,75 mm)\n후강이 두껍고 기계강도 큼.",
    subject: "전기설비",
    topic: "배선공사",
    source: "preset",
    hint: "후강=안지름 짝수, 박강=바깥지름 홀수",
  },
  {
    id: "f-work-raceway",
    front: "금속덕트·금속몰드·라이팅덕트 차이?",
    back: "금속덕트: 다수 전선 수용 큰 통로 (전기실·간선)\n금속몰드: 노출 소규모 배선 보호 (증설·리모델링)\n라이팅덕트: 조명기구를 임의 위치에 접속 (상점·전시)",
    subject: "전기설비",
    topic: "배선공사",
    source: "preset",
  },
  {
    id: "f-work-duct-fill",
    front: "금속덕트 내 전선 총단면적 제한?",
    back: "전선 절연물 포함 총단면적은 덕트 내 단면적의 20% 이하.\n(제어·신호용으로 출입만 하는 경우 50% 이하 적용 가능.)\n방열·점검·증설 여유 확보 목적.",
    subject: "전기설비",
    topic: "배선공사",
    source: "preset",
    hint: "금속덕트 일반 20% 이하",
  },
  {
    id: "f-work-cable-tray",
    front: "케이블 트레이 공사의 특징?",
    back: "사다리형·바닥밀폐형 등 트레이에 케이블을 포설.\n점검·증설 용이, 방열 양호 → 전기실·플랜트 간선에 적합.\n트레이는 접지하고, 케이블은 난연성 사용 권장.",
    subject: "전기설비",
    topic: "배선공사",
    source: "preset",
  },
  {
    id: "f-work-floor-duct",
    front: "플로어덕트·셀룰러덕트 공사?",
    back: "콘크리트 바닥 속에 덕트를 매입해 사무실 등에서 바닥 임의 위치로 전원·통신 인출.\n인출구(정션박스) 통해 분기.\n수분 침투 우려 장소엔 부적합.",
    subject: "전기설비",
    topic: "배선공사",
    source: "preset",
  },
  {
    id: "f-work-bus-duct",
    front: "버스덕트(부스덕트) 공사란?",
    back: "절연 지지된 도체 모선을 금속함에 수용한 대전류 간선 방식.\n대용량 빌딩·공장 수직간선에 사용.\n접속 용이, 사고 시 구간 분리 쉬움. 발열·진동 관리 필요.",
    subject: "전기설비",
    topic: "배선공사",
    source: "preset",
    hint: "대전류 간선 — 모선을 함에 수용",
  },
  {
    id: "f-work-underground",
    front: "지중 케이블 매설 방식 3가지?",
    back: "1. 직접매설식: 트로프·모래로 직접 묻음 (저비용, 보수 어려움)\n2. 관로식: 관에 케이블 입선 (증설·보수 용이)\n3. 전력구(암거)식: 사람 출입 통로에 포설 (대도시 대용량)\n중량물 통과 장소는 매설깊이 깊게.",
    subject: "전기설비",
    topic: "배선공사",
    source: "preset",
    hint: "직매·관로·전력구",
  },
  {
    id: "f-work-wet-location",
    front: "습기·물기 있는 장소의 배선공사 제한?",
    back: "금속관·합성수지관·케이블 공사 등 보호된 방식만 허용.\n애자·금속몰드·금속덕트 등 노출 취약 공사는 제한.\n방수형 박스·부속 사용, 접지 철저.",
    subject: "전기설비",
    topic: "배선공사",
    source: "preset",
  },
  {
    id: "f-work-explosive",
    front: "폭연성·가연성 분진/가스 장소의 배선?",
    back: "방폭형 기기 사용. 금속관 공사(두께 충분) 또는 케이블(MI·개장) 공사.\n관 접속부는 패킹·실링피팅으로 밀폐.\n전기불꽃·고온이 점화원이 되지 않도록 설계.",
    subject: "전기설비",
    topic: "배선공사",
    source: "preset",
    hint: "방폭 + 금속관/케이블 + 실링",
  },
  {
    id: "f-work-support-distance",
    front: "전선관·케이블 지지점 간격 원칙?",
    back: "관·케이블이 처지거나 외력에 손상되지 않도록 새들·클리트로 일정 간격 고정.\n금속관 일반 2 m 이하, 케이블 일반 2 m 이하(조영재 따라 시), 굴곡부·박스 근처는 더 짧게.\n수직 포설 시 자중 지지 추가.",
    subject: "전기설비",
    topic: "배선공사",
    source: "preset",
    hint: "대략 2 m 이하 — 굴곡부 더 짧게",
  },
  {
    id: "f-work-bend-radius",
    front: "케이블 굴곡 반지름 기준?",
    back: "케이블 손상 방지를 위해 굴곡반지름은 케이블 바깥지름의 일정 배수 이상.\n저압 단심 약 8배, 다심 약 6배 이상(시스·도체 종류별 상이).\n과도한 굽힘은 절연·도체 손상.",
    subject: "전기설비",
    topic: "배선공사",
    source: "preset",
    hint: "외경의 6~8배 이상",
  },

  // ───────────────────────── 옥내배선 ─────────────────────────
  {
    id: "f-indoor-three-phase-4wire",
    front: "저압 3상 4선식(380/220 V) 구성?",
    back: "3개 상선(L1·L2·L3) + 중성선(N).\n상-중성 220 V(단상부하), 상-상 380 V(3상부하).\n선간 $V_L = \\sqrt{3} \\times V_p$ 관계. 한국 일반 빌딩 표준.",
    subject: "전기설비",
    topic: "옥내배선",
    source: "preset",
    hint: "상-N 220 / 상-상 380",
    example: {
      question: "3상 4선식에서 상전압(상-중성)이 220 V일 때 선간전압은?",
      solution: [
        "$V_L = \\sqrt{3} \\times V_p$",
        "$V_L = 1.732 \\times 220 \\approx 381\\ \\text{V}$",
      ],
      answer: "약 380 V",
    },
  },
  {
    id: "f-indoor-load-estimate",
    front: "옥내 부하설비 용량 산정 기본 개념?",
    back: "표준부하밀도(VA/m²) × 바닥면적 + 부분부하 + 가산부하.\n주택·점포 등 용도별 표준부하 적용 후 수용률·부등률 반영해 변압기·간선 용량 결정.",
    subject: "전기설비",
    topic: "옥내배선",
    source: "preset",
    hint: "표준부하밀도 × 면적",
  },
  {
    id: "f-indoor-demand-factor",
    front: "수용률·부등률·부하율의 정의?",
    back: "수용률 $= \\dfrac{\\text{최대수용전력}}{\\text{설비용량}} \\times 100$\n부등률 $= \\dfrac{\\sum \\text{개별 최대전력}}{\\text{합성 최대전력}} (\\geq 1)$\n부하율 $= \\dfrac{\\text{평균전력}}{\\text{최대전력}} \\times 100$",
    subject: "전기설비",
    topic: "옥내배선",
    source: "preset",
    hint: "부등률은 항상 1 이상",
    example: {
      question: "설비용량 100 kW, 최대수용전력 60 kW일 때 수용률은?",
      solution: [
        "수용률 $= \\dfrac{\\text{최대수용전력}}{\\text{설비용량}} \\times 100$",
        "$= \\dfrac{60}{100} \\times 100 = 60\\%$",
      ],
      answer: "60 %",
    },
  },
  {
    id: "f-indoor-panel",
    front: "분전반의 역할과 구성?",
    back: "간선을 받아 여러 분기회로로 분배·보호하는 함체.\n구성: 주차단기(메인) + 분기차단기(MCB) + 모선(부스바) + 단자대 + 표시.\n예비회로·회선표(결선도) 부착 권장.",
    subject: "전기설비",
    topic: "옥내배선",
    source: "preset",
  },
  {
    id: "f-indoor-circuit-diagram",
    front: "옥내배선 도면 기호 — 일반 부호?",
    back: "● 또는 ⊗ : 점멸기(스위치)\n콘센트: 원에 두 선 기호\n전등: ○ 안에 ×\n분전반: 사각형 빗금\n천장 은폐배선은 실선, 노출은 점선 등 규약 기호 사용.",
    subject: "전기설비",
    topic: "옥내배선",
    source: "preset",
  },
  {
    id: "f-indoor-three-way-wiring",
    front: "3로 스위치 2개소 점멸 결선 원리?",
    back: "전원 → 3로(공통 C) → 두 가닥(L1·L2 진행선) → 반대편 3로(공통 C) → 등기구 → 중성선.\n두 스위치 중 어느 쪽을 조작해도 회로 통·단 전환.\n진행선 2가닥이 핵심.",
    subject: "전기설비",
    topic: "옥내배선",
    source: "preset",
    hint: "공통-공통, 사이에 진행선 2가닥",
  },
  {
    id: "f-indoor-neutral-rule",
    front: "옥내배선에서 중성선(N) 취급 원칙?",
    back: "중성선은 보호도체(PE)와 구분, 청색.\n중성선에 단독 개폐기·과전류차단기 설치 원칙적 금지(동시차단 또는 비차단).\n다선식에서 중성선 단선 시 과전압 위험.",
    subject: "전기설비",
    topic: "옥내배선",
    source: "preset",
    hint: "N 단독 차단 금지 — 단선 시 위험",
  },
  {
    id: "f-indoor-lamp-circuit",
    front: "전등 1개를 1개 스위치로 점멸하는 단극 결선?",
    back: "전원 상선(L) → 스위치 → 등기구 → 중성선(N).\n스위치는 반드시 상선(L)에 설치(중성선 절단 금지).\n점멸기를 N에 두면 등은 꺼져도 충전 상태 → 감전 위험.",
    subject: "전기설비",
    topic: "옥내배선",
    source: "preset",
    hint: "스위치는 무조건 상선(L)에",
  },
  {
    id: "f-indoor-pilot-switch",
    front: "파일럿(표시등) 스위치·위치표시등의 용도?",
    back: "파일럿램프: 부하 ON 상태 표시(켜졌는지 멀리서 확인)\n위치표시등(형광·네온): 어두운 곳에서 스위치 위치 안내(OFF 시 약하게 점등)\n현관·계단·기계실 등에 활용.",
    subject: "전기설비",
    topic: "옥내배선",
    source: "preset",
  },
  {
    id: "f-indoor-branch-capacity",
    front: "분기회로 1회로당 콘센트 수·용량 관리?",
    back: "한 분기회로에 과다 콘센트 집중 금지(동시사용으로 과전류).\n일반 콘센트 분기 16~20 A급, 부하 큰 기기(에어컨·전열)는 전용회로.\n분기 전선 굵기는 분기차단기 정격에 적합하게.",
    subject: "전기설비",
    topic: "옥내배선",
    source: "preset",
    hint: "큰 부하 = 전용회로",
  },
  {
    id: "f-indoor-three-phase-balance",
    front: "단상부하의 3상 평형 배분 이유?",
    back: "3상 4선식에서 단상부하를 L1·L2·L3에 고르게 분산해야\n중성선 전류·전압불평형·손실 최소화.\n불평형 시 중성선 과열·기기 전압변동 발생.",
    subject: "전기설비",
    topic: "옥내배선",
    source: "preset",
    hint: "불평형 → 중성선 과열",
  },
  {
    id: "f-indoor-conductor-min",
    front: "옥내 저압 분기회로 최소 전선 굵기 개념?",
    back: "기계적 강도·허용전류·전압강하 모두 만족해야 함.\n일반 분기 동 도체 최소 단면적은 통상 2.5 mm² 이상(전등 전용 등 일부 1.5 mm²).\n전압강하는 간선+분기 합산으로 관리(권장 표준전압의 수 % 이내).",
    subject: "전기설비",
    topic: "옥내배선",
    source: "preset",
    hint: "강도·허용전류·전압강하 동시 만족",
  },

  // ───────────────────────── 접지 ─────────────────────────
  {
    id: "f-ground-kec-system",
    front: "KEC 계통접지 방식 표기(TN·TT·IT)?",
    back: "첫 글자: 전원측 대지 관계 (T 직접접지, I 비접지/임피던스)\n둘째 글자: 노출도전부 대지 관계 (T 독립접지, N 전원중성선 연결).\nTN은 PE·N 배치에 따라 TN-S / TN-C / TN-C-S 세분.",
    subject: "전기설비",
    topic: "접지",
    source: "preset",
    hint: "1번=전원, 2번=기기 / TN·TT·IT",
  },
  {
    id: "f-ground-tn-types",
    front: "TN-S / TN-C / TN-C-S 차이?",
    back: "TN-S: 보호도체(PE)와 중성선(N)을 전 구간 분리\nTN-C: PE와 N을 하나(PEN)로 겸용\nTN-C-S: 전원측 PEN → 어느 지점부터 PE/N 분리.\n분리(S)할수록 노이즈·감전 안전성 유리.",
    subject: "전기설비",
    topic: "접지",
    source: "preset",
    hint: "S=분리, C=겸용(PEN)",
  },
  {
    id: "f-ground-purpose",
    front: "접지의 목적(기능별)?",
    back: "1. 감전 보호(기기 외함 대지전위 억제)\n2. 이상전압 억제(뇌·혼촉)\n3. 보호장치 확실 동작(고장전류 경로 확보)\n4. 정전기·노이즈 대책(기능접지).",
    subject: "전기설비",
    topic: "접지",
    source: "preset",
    hint: "감전·이상전압·동작·노이즈",
  },
  {
    id: "f-ground-soil-resistivity",
    front: "접지저항을 낮추는 방법?",
    back: "1. 접지극 길이·개수 증가(병렬·심타)\n2. 접지봉 깊게(심타) 박기\n3. 접지저감제(도전성 물질) 사용\n4. 메시·판상 접지로 접촉면적 확대\n토양 고유저항이 작을수록 유리.",
    subject: "전기설비",
    topic: "접지",
    source: "preset",
    hint: "길게·여러개·심타·저감제",
  },
  {
    id: "f-ground-equipotential",
    front: "등전위본딩(Equipotential Bonding)이란?",
    back: "건물 내 금속체(수도관·구조철골·PE 등)를 서로 접속해 전위차를 없애 감전·아크 위험 저감.\n주등전위본딩(인입부)과 보조(국부)등전위본딩으로 구성.",
    subject: "전기설비",
    topic: "접지",
    source: "preset",
    hint: "금속체 전위차 제거",
  },
  {
    id: "f-ground-parallel-rod",
    front: "접지봉 병렬 접속 시 합성접지저항 경향?",
    back: "여러 접지극 병렬 → 합성저항 감소(단, 상호 간섭으로 1/n 보다 큼).\n근사: $R_{합} \\approx \\dfrac{R}{n} \\times (1+\\lambda)$ (간섭계수 λ).\n극 간격을 충분히 벌릴수록 효과적.",
    subject: "전기설비",
    topic: "접지",
    source: "preset",
    example: {
      question: "단독 50 Ω 접지봉 4개를 간섭 없이 이상적으로 병렬 접속 시 합성저항 근사값은?",
      solution: [
        "이상적 병렬: $R_{합} \\approx \\dfrac{R}{n}$",
        "$= \\dfrac{50}{4} = 12.5\\ \\Omega$ (실제는 간섭으로 더 큼)",
      ],
      answer: "약 12.5 Ω (실제는 그보다 큼)",
    },
  },
  {
    id: "f-ground-pe-color",
    front: "보호도체(PE)의 색상·식별과 단면적 원칙?",
    back: "색상: 녹색-노랑 줄무늬 전용.\n단면적: 상도체 단면적에 따라 산정(상도체 ≤16 mm²면 동일, 16~35는 16 mm², 그 이상은 상도체의 1/2 등 KEC 표 적용).\n별도 산정식(열적등가)으로도 가능.",
    subject: "전기설비",
    topic: "접지",
    source: "preset",
    hint: "녹/황, 상도체 크기로 PE 단면적",
  },
  {
    id: "f-ground-step-touch",
    front: "보폭전압·접촉전압이란?",
    back: "보폭전압(보폭전위): 사고 시 사람 양발 사이(약 1 m) 지표 전위차.\n접촉전압: 접지된 기기 외함과 사람 손-발 사이 전위차.\n두 전압을 인체 허용한계 이하로 억제하도록 접지 설계.",
    subject: "전기설비",
    topic: "접지",
    source: "preset",
    hint: "보폭=발-발, 접촉=손-발",
  },
  {
    id: "f-ground-neutral-multi",
    front: "중성점 다중접지 방식의 의미?",
    back: "배전선로 중성선을 일정 간격마다 여러 곳에서 접지(22.9 kV-Y 배전).\n지락전류 경로 확보 → 보호장치 신속 동작·이상전압 억제.\n중성선·접지선 단선 시 위험 증가 주의.",
    subject: "전기설비",
    topic: "접지",
    source: "preset",
    hint: "22.9 kV-Y = 중성점 다중접지",
  },
  {
    id: "f-ground-fault-loop",
    front: "고장(지락) 루프 임피던스와 보호동작 관계?",
    back: "지락 시 고장전류 $I_f = \\dfrac{V}{Z_{loop}}$.\n루프 임피던스가 작아야 충분한 고장전류가 흘러 차단기·퓨즈가 규정 시간 내 동작.\n접지·본딩 불량은 보호 부동작 원인.",
    subject: "전기설비",
    topic: "접지",
    source: "preset",
    hint: "루프 Z↓ → 고장전류↑ → 확실 차단",
    example: {
      question:
        "지락 루프 임피던스 $Z_{loop} = 1.1\\ \\Omega$, 상전압 220 V일 때 예상 지락전류는?",
      solution: [
        "$I_f = \\dfrac{V}{Z_{loop}}$",
        "$I_f = \\dfrac{220}{1.1} = 200\\ \\text{A}$",
      ],
      answer: "$I_f = 200\\ \\text{A}$",
    },
  },
  {
    id: "f-ground-electrode-type",
    front: "접지극의 종류?",
    back: "봉형(접지봉), 판형(접지판), 대상(테이프·평판), 망상(메시), 기초접지극(건물 기초철근 활용).\n수도관 등을 접지극으로 단독 사용은 제한.\n부식·기계강도·매설깊이 고려해 선정.",
    subject: "전기설비",
    topic: "접지",
    source: "preset",
  },
  {
    id: "f-ground-extra-low",
    front: "SELV·PELV·FELV 차이?",
    back: "SELV: 안전특별저압, 절연된 비접지 회로(접지 안 함)\nPELV: 보호특별저압, SELV와 같으나 접지 가능\nFELV: 기능특별저압, 안전 분리·절연 요건 불충족 → 추가 보호 필요.\n특별저압은 감전 위험을 본질적으로 낮춤.",
    subject: "전기설비",
    topic: "접지",
    source: "preset",
    hint: "S=비접지, P=접지가능, F=기능용",
  },

  // ───────────────────────── 피뢰·보호 ─────────────────────────
  {
    id: "f-lps-rolling-sphere",
    front: "회전구체법(보호범위 산정)이란?",
    back: "낙뢰 보호레벨별 반지름의 가상 구체를 구조물 위로 굴려, 구체가 닿지 않는 영역을 보호범위로 간주.\n보호레벨 I일수록 구체 반지름 작음(엄격).\n수뢰부·메시법과 함께 LPS 설계에 사용.",
    subject: "전기설비",
    topic: "피뢰·보호",
    source: "preset",
    hint: "구체가 못 닿는 곳 = 보호",
  },
  {
    id: "f-lps-components",
    front: "외부 피뢰시스템(LPS) 3요소?",
    back: "1. 수뢰부 시스템: 뇌격을 받는 부분(돌침·수평도체·메시)\n2. 인하도선: 뇌전류를 접지로 유도\n3. 접지극 시스템: 뇌전류를 대지로 방류\n세 요소를 저임피던스로 연결.",
    subject: "전기설비",
    topic: "피뢰·보호",
    source: "preset",
    hint: "수뢰부 → 인하도선 → 접지",
  },
  {
    id: "f-lps-down-conductor",
    front: "인하도선 설치 원칙?",
    back: "뇌전류를 최단·직선 경로로 분산 유도.\n보호레벨별 일정 간격으로 복수 배치(둘레 따라 균등).\n급격한 굴곡 회피, 측면 섬락 방지 위해 등전위본딩·이격거리 확보.",
    subject: "전기설비",
    topic: "피뢰·보호",
    source: "preset",
    hint: "최단·직선·복수·등간격",
  },
  {
    id: "f-lps-arrester-la",
    front: "피뢰기(LA)의 역할과 제한전압?",
    back: "선로의 이상전압(뇌·개폐서지)에서 기기를 보호.\n평상시 절연, 서지 시 도통해 대지로 방전 후 속류 차단.\n제한전압(방전 중 단자전압)이 낮을수록 보호성능 우수.\n변압기·수전설비 보호에 필수.",
    subject: "전기설비",
    topic: "피뢰·보호",
    source: "preset",
    hint: "제한전압 낮을수록 보호 양호",
  },
  {
    id: "f-lps-arrester-position",
    front: "피뢰기 설치 위치 원칙?",
    back: "보호대상(변압기 등)에 최대한 가깝게, 인입 1차측에 설치.\n피뢰기와 피보호기기 간 거리(이격) 길면 진행파 반사로 보호효과 저하.\n피뢰기 접지는 저저항 단독·연접 접지로.",
    subject: "전기설비",
    topic: "피뢰·보호",
    source: "preset",
    hint: "보호기기에 가깝게 = 효과↑",
  },
  {
    id: "f-lps-spd-position",
    front: "SPD(서지보호장치)와 피뢰기(LA)의 구분?",
    back: "LA(피뢰기): 주로 고압·특고압 전력설비의 이상전압 보호.\nSPD: 저압 옥내 회로·정보통신기기의 과도전압 보호(Type 1/2/3 다단 협조).\n둘 다 서지 흡수·전위 제한이 목적이나 적용 전압대·규격이 다름.",
    subject: "전기설비",
    topic: "피뢰·보호",
    source: "preset",
    hint: "LA=고압측, SPD=저압·정보기기",
  },
  {
    id: "f-lps-bonding",
    front: "피뢰등전위본딩의 필요성?",
    back: "뇌전류 유입 시 LPS·금속체·전기설비 간 전위차로 인한 섬락·기기손상 방지.\n인입 금속배관·전력선·통신선을 본딩바에 SPD 또는 직접 접속.\n뇌보호영역(LPZ) 경계마다 본딩.",
    subject: "전기설비",
    topic: "피뢰·보호",
    source: "preset",
    hint: "LPZ 경계마다 본딩",
  },
  {
    id: "f-lps-protection-level",
    front: "뇌보호레벨(LPL) I~IV의 의미?",
    back: "구조물 중요도·위험도에 따라 요구 보호효율 차등.\nLPL I 가장 엄격(큰 첨두전류 가정, 작은 회전구체 반지름·촘촘한 메시·짧은 인하도선 간격).\nIV로 갈수록 완화. 위험성 평가로 레벨 선정.",
    subject: "전기설비",
    topic: "피뢰·보호",
    source: "preset",
    hint: "I = 가장 엄격",
  },
  {
    id: "f-lps-mesh",
    front: "메시법(망상 도체) 보호 개념?",
    back: "옥상에 일정 간격 격자(메시) 도체망을 깔아 평탄한 지붕을 보호.\n보호레벨별 메시 간격 차등(레벨 I이 가장 촘촘).\n돌출부·모서리는 수뢰부 추가.",
    subject: "전기설비",
    topic: "피뢰·보호",
    source: "preset",
    hint: "평지붕 보호 — 레벨↑ 촘촘",
  },
  {
    id: "f-lps-grounding-r",
    front: "피뢰설비 접지저항 권장값과 형태?",
    back: "낮을수록 좋고(통상 10 Ω 이하 목표), 형태는 환상·방사상·기초접지 등.\n뇌전류는 고주파 성격 → 임피던스(서지 임피던스) 관점에서 짧고 직선적인 접지가 유리.\n타 접지와 통합접지로 구성 가능.",
    subject: "전기설비",
    topic: "피뢰·보호",
    source: "preset",
    hint: "10 Ω 이하 목표 + 저임피던스",
  },
  {
    id: "f-lps-air-termination",
    front: "수뢰부(돌침·수평도체) 배치 원칙?",
    back: "구조물 모서리·돌출부·높은 부분 우선 보호.\n돌침은 보호각/회전구체/메시 중 적합한 방법으로 보호범위 산정.\n금속 지붕·난간을 자연적 구성부재로 활용 가능.",
    subject: "전기설비",
    topic: "피뢰·보호",
    source: "preset",
    hint: "모서리·돌출부 우선",
  },
  {
    id: "f-lps-side-flash",
    front: "측면 섬락(side flash)과 이격거리?",
    back: "인하도선과 인접 금속체 사이 전위차가 절연내력을 넘으면 공기 중 방전(섬락) 발생.\n방지: 이격거리 확보 또는 등전위본딩.\n이격거리는 뇌전류 분배·경로 길이에 비례해 산정.",
    subject: "전기설비",
    topic: "피뢰·보호",
    source: "preset",
    hint: "이격 확보 or 본딩으로 방지",
  },

  // ───────────────────────── 차단기·보호장치 ─────────────────────────
  {
    id: "f-prot-fuse-vs-breaker",
    front: "퓨즈와 차단기의 비교?",
    back: "퓨즈: 가용체 용단으로 차단, 한 번 동작 후 교체, 동작 빠르고 한류 성능 우수, 저렴.\n차단기: 기계적 개폐로 차단·재투입 가능, 특성 조정·부가기능(누전 등) 가능.\n둘 다 과전류 보호용.",
    subject: "전기설비",
    topic: "차단기·보호장치",
    source: "preset",
    hint: "퓨즈=교체식 한류, CB=재투입",
  },
  {
    id: "f-prot-breaking-capacity",
    front: "차단기 정격차단용량(차단전류)이란?",
    back: "차단기가 안전하게 차단할 수 있는 최대 단락전류.\n설치점 예상 단락전류보다 차단기 정격차단용량이 커야 함.\n부족하면 단락 시 차단기 파손·화재.\n[kA] 단위로 표기.",
    subject: "전기설비",
    topic: "차단기·보호장치",
    source: "preset",
    hint: "예상 단락전류 < 정격차단용량",
  },
  {
    id: "f-prot-short-circuit-calc",
    front: "단락전류 개략 계산(%임피던스법)?",
    back: "$I_s = \\dfrac{100}{\\%Z} \\times I_n$\n$\\%Z$ 합성 퍼센트임피던스, $I_n$ 정격(기준)전류.\n%Z가 작을수록 단락전류 큼 → 차단용량 큰 차단기 필요.",
    subject: "전기설비",
    topic: "차단기·보호장치",
    source: "preset",
    hint: "%Z 작을수록 단락전류 큼",
    example: {
      question: "정격전류 100 A, 합성 %Z = 5 %일 때 단락전류는?",
      solution: [
        "$I_s = \\dfrac{100}{\\%Z} \\times I_n$",
        "$I_s = \\dfrac{100}{5} \\times 100$",
        "$I_s = 20 \\times 100 = 2000\\ \\text{A} = 2\\ \\text{kA}$",
      ],
      answer: "$I_s = 2\\ \\text{kA}$",
    },
  },
  {
    id: "f-prot-disconnector",
    front: "단로기(DS)·부하개폐기(LBS)·차단기(CB) 차이?",
    back: "단로기(DS): 무부하 상태에서만 개폐(점검 시 회로 확실 분리, 소호능력 없음)\n부하개폐기(LBS): 정상 부하전류 개폐 가능, 단락차단은 불가(퓨즈와 조합)\n차단기(CB): 정상·사고(단락)전류 모두 차단.",
    subject: "전기설비",
    topic: "차단기·보호장치",
    source: "preset",
    hint: "DS=무부하, LBS=부하, CB=사고",
  },
  {
    id: "f-prot-relay-types",
    front: "보호계전기 종류(동작 요소별)?",
    back: "과전류계전기(OCR), 지락계전기(GR/OCGR), 과전압(OVR)·부족전압(UVR), 거리계전기, 차동계전기(변압기·발전기 내부 고장), 방향계전기.\nPT·CT로 입력 받아 차단기 트립.",
    subject: "전기설비",
    topic: "차단기·보호장치",
    source: "preset",
    hint: "OCR·GR·OVR·UVR·차동",
  },
  {
    id: "f-prot-cb-arc-medium",
    front: "고압 차단기 소호 매질별 종류?",
    back: "VCB(진공차단기): 진공 중 소호, 보수 적음(현재 배전 주력)\nGCB(가스차단기, SF6): 고압·송전\nOCB(유입), ABB(공기), MBB(자기) 등.\n매질이 아크를 신속 소멸시켜 차단.",
    subject: "전기설비",
    topic: "차단기·보호장치",
    source: "preset",
    hint: "배전 주력 = VCB(진공)",
  },
  {
    id: "f-prot-trip-curve",
    front: "배선용차단기 트립곡선(B·C·D)?",
    back: "순시트립 배율 기준:\nB형: 정격의 3~5배에서 순시(저관성 부하·일반)\nC형: 5~10배(일반 동력·혼합 부하)\nD형: 10~20배(돌입전류 큰 모터·변압기)\n과부하는 열동, 단락은 전자식 순시.",
    subject: "전기설비",
    topic: "차단기·보호장치",
    source: "preset",
    hint: "B<C<D (순시배율 커짐)",
  },
  {
    id: "f-prot-elb-sensitivity",
    front: "누전차단기 감도·동작시간 분류?",
    back: "고감도: 정격감도전류 30 mA 이하(인체감전 보호, 욕실·콘센트)\n중·저감도: 50 mA 이상(설비 보호)\n동작시간: 고속형(0.1초 이내), 시연형(선택차단용).\n인체 보호는 30 mA·0.03초 이하가 기준.",
    subject: "전기설비",
    topic: "차단기·보호장치",
    source: "preset",
    hint: "감전보호 = 30 mA / 0.03 s",
  },
  {
    id: "f-prot-selectivity",
    front: "보호협조(선택차단)란?",
    back: "사고 시 사고에 가장 가까운 차단기만 동작하고 상위는 유지 → 정전범위 최소화.\n상·하위 차단기 동작특성(전류·시간)에 시간차·전류차를 둠.\nELB는 감도·시연 협조, CB는 시한차 협조.",
    subject: "전기설비",
    topic: "차단기·보호장치",
    source: "preset",
    hint: "사고 가까운 것만 동작",
  },
  {
    id: "f-prot-pf-improve",
    front: "역률 개선용 콘덴서(진상콘덴서)의 효과?",
    back: "지상 무효전력을 진상으로 보상 → 역률 개선.\n효과: 선로손실·전압강하 감소, 설비 여유 증대, 전기요금 절감.\n방전저항·직렬리액터(고조파 대책)와 함께 설치.",
    subject: "전기설비",
    topic: "차단기·보호장치",
    source: "preset",
    hint: "무효전력 보상 → 손실↓",
    example: {
      question:
        "유효전력 80 kW, 역률 0.8(지상)을 1.0으로 개선할 때 필요한 콘덴서 용량(무효전력)은?",
      solution: [
        "초기 무효전력 $Q_1 = P \\tan\\theta_1$, $\\cos\\theta_1=0.8 \\Rightarrow \\tan\\theta_1=0.75$",
        "$Q_1 = 80 \\times 0.75 = 60\\ \\text{kVar}$",
        "역률 1.0이면 $Q_2 = 0$",
        "필요 콘덴서 $Q_c = Q_1 - Q_2 = 60\\ \\text{kVar}$",
      ],
      answer: "약 60 kVar",
    },
  },
  {
    id: "f-prot-mof-ct-pt",
    front: "계기용 변성기 CT·PT(VT)·MOF의 역할?",
    back: "CT(변류기): 큰 전류를 표준 소전류(예 5 A)로 변환\nPT/VT(계기용 변압기): 고전압을 저전압(예 110 V)으로 변환\nMOF(계기용 변성기함, PT+CT): 전력량 계량용 통합 변성기.\n2차 개방(CT)·단락(PT)은 금지.",
    subject: "전기설비",
    topic: "차단기·보호장치",
    source: "preset",
    hint: "CT 2차 개방 금지 / PT 2차 단락 금지",
  },
  {
    id: "f-prot-overload-thermal",
    front: "전동기 과부하 보호(열동계전기 EOCR/THR)?",
    back: "전동기 과부하·결상·구속 시 권선 과열 방지.\n바이메탈 열동형 또는 전자식(EOCR)으로 전류 감시 후 마그네틱 접촉기 트립.\n정격전류 기준 동작값 설정, 단락보호는 차단기·퓨즈가 별도 담당.",
    subject: "전기설비",
    topic: "차단기·보호장치",
    source: "preset",
    hint: "과부하=열동, 단락=차단기",
  },

  // ───────────────────────── 변전·배전 ─────────────────────────
  {
    id: "f-dist-standard-voltage",
    front: "한국 저압 표준전압(공칭전압)?",
    back: "단상 220 V, 3상 380 V(3상 4선식 380/220 V).\n허용오차 통상 ±10% 내외 관리.\n과거 단상 110 V는 220 V로 승압 완료.",
    subject: "전기설비",
    topic: "변전·배전",
    source: "preset",
    hint: "단상 220 / 3상 380",
  },
  {
    id: "f-dist-pole-transformer",
    front: "주상변압기(P.Tr)의 역할?",
    back: "배전선로 22.9 kV-Y를 수용가 사용전압(380/220 V)으로 강압.\n전봇대에 설치, 1차 컷아웃스위치(COS)·2차 저압인입.\n중성선 다중접지와 연계.",
    subject: "전기설비",
    topic: "변전·배전",
    source: "preset",
    hint: "22.9 kV → 380/220 V 강압",
  },
  {
    id: "f-dist-distribution-system",
    front: "배전방식 — 수지식·환상식·망상식 비교?",
    back: "수지식(방사상): 단순·경제적, 사고 시 정전범위 큼(농어촌)\n환상식(루프): 양방향 공급, 신뢰도 향상\n망상식(네트워크): 다중경로, 신뢰도 최고지만 고가(대도시 중심부).",
    subject: "전기설비",
    topic: "변전·배전",
    source: "preset",
    hint: "수지<환상<망상 (신뢰도·비용↑)",
  },
  {
    id: "f-dist-power-loss",
    front: "배전선로 전력손실 식과 저감 대책?",
    back: "선로손실 $P_\\ell = I^2 R$ (3상은 $3 I^2 R$).\n저감: 전압 승압(전류↓), 역률 개선(전류↓), 굵은 도체, 부하 평형, 부하중심 변압기 배치.",
    subject: "전기설비",
    topic: "변전·배전",
    source: "preset",
    hint: "손실 ∝ I² → 전압·역률↑",
    example: {
      question:
        "선로저항 0.5 Ω에 25 A가 흐르는 단상 2선식 1가닥. 왕복 도체 손실 총합은?",
      solution: [
        "1가닥 손실 $= I^2 R = 25^2 \\times 0.5 = 312.5\\ \\text{W}$",
        "왕복(2가닥) 총합 $= 2 \\times 312.5 = 625\\ \\text{W}$",
      ],
      answer: "총 625 W",
    },
  },
  {
    id: "f-dist-voltage-up",
    front: "송·배전 전압을 높이면 얻는 이점?",
    back: "같은 전력 전송 시 전류 감소 → ① 선로손실($I^2R$) 감소 ② 전압강하 감소 ③ 도체 굵기·중량 절감.\n단, 절연비용·안전이격은 증가.\n전압 n배 → 동일전력에서 손실 $1/n^2$.",
    subject: "전기설비",
    topic: "변전·배전",
    source: "preset",
    hint: "전압 n배 → 손실 1/n²",
    example: {
      question: "송전전압을 2배로 높이면 동일 전력·동일 도체에서 선로손실은?",
      solution: [
        "동일전력: $P=VI \\Rightarrow I \\propto \\dfrac{1}{V}$, 전압 2배 → 전류 1/2",
        "손실 $\\propto I^2 \\Rightarrow \\left(\\dfrac{1}{2}\\right)^2 = \\dfrac{1}{4}$",
      ],
      answer: "원래의 1/4로 감소",
    },
  },
  {
    id: "f-dist-pf-economy",
    front: "역률이 낮으면 생기는 문제?",
    back: "같은 유효전력에 더 큰 전류 필요 → 선로손실·전압강하 증가, 설비용량 잠식, 전기요금 역률할증.\n개선: 진상콘덴서·동기조상기·인버터.\n역률 $\\cos\\theta = P/S$.",
    subject: "전기설비",
    topic: "변전·배전",
    source: "preset",
    hint: "역률↓ → 전류↑ → 손실↑",
  },
  {
    id: "f-dist-substation-type",
    front: "수변전설비 — 큐비클(폐쇄배전반)·GIS?",
    back: "큐비클식: 차단기·변압기·계기 등을 금속함체에 일괄 수용(빌딩 수전실, 안전·콤팩트)\nGIS(가스절연개폐장치): SF6 가스로 절연, 초소형·고신뢰(도심 변전소).\n개방형 대비 안전·공간 유리.",
    subject: "전기설비",
    topic: "변전·배전",
    source: "preset",
    hint: "큐비클=폐쇄형, GIS=가스절연",
  },
  {
    id: "f-dist-cos-ass",
    front: "수전설비 보호기기 COS·PF·ASS?",
    back: "COS(컷아웃스위치): 주상변압기 1차 보호·개폐(퓨즈 내장)\nPF(전력퓨즈): 고압 단락보호(한류형)\nASS(자동고장구분개폐기): 수용가 사고를 선로에서 자동 구분·분리(파급 방지).",
    subject: "전기설비",
    topic: "변전·배전",
    source: "preset",
    hint: "ASS=사고 자동 구분 분리",
  },
  {
    id: "f-dist-neutral-grounding",
    front: "송전계통 중성점 접지방식 비교?",
    back: "비접지: 1선지락 시 지락전류 작음, 이상전압 큼(소규모)\n직접접지: 지락전류 큼·보호 확실, 이상전압 낮음(154 kV↑ 채택)\n저항/소호리액터접지: 절충(지락전류 제한).\n한국 22.9 kV-Y는 중성점 다중접지.",
    subject: "전기설비",
    topic: "변전·배전",
    source: "preset",
    hint: "직접접지=이상전압↓·고장전류↑",
  },
  {
    id: "f-dist-overhead-vs-underground",
    front: "가공배전 vs 지중배전 비교?",
    back: "가공: 건설·보수비 저렴, 사고 발견·복구 빠름, 미관·안전 불리.\n지중: 미관·태풍/염해에 강함, 공급신뢰도 우수, 건설·고장복구 비용 큼.\n도심·관광지는 지중화 추진.",
    subject: "전기설비",
    topic: "변전·배전",
    source: "preset",
    hint: "가공=싸고 빠름, 지중=안전·미관",
  },
  {
    id: "f-dist-recloser-sectionalizer",
    front: "리클로저·섹셔널라이저의 기능?",
    back: "리클로저(R/C): 일시고장 시 자동 차단·재투입 반복 → 순간고장 자동복구.\n섹셔널라이저(S/E): 자체 차단능력 없이 리클로저 무전압 구간에 사고구간을 분리.\n→ 배전 신뢰도 향상.",
    subject: "전기설비",
    topic: "변전·배전",
    source: "preset",
    hint: "리클로저=재투입, 섹셔널=구간분리",
  },
  {
    id: "f-dist-transformer-connection",
    front: "배전용 변압기 결선 — Δ-Y, Y-Δ, V결선?",
    back: "Δ-Y: 2차 중성점 인출(3상4선 380/220 V 공급)에 유리.\nY-Δ: 강압·고조파 순환에 유리.\nV결선: 변압기 2대로 3상 공급(고장 대응), 출력은 Δ의 약 57.7%로 감소.",
    subject: "전기설비",
    topic: "변전·배전",
    source: "preset",
    hint: "V결선 출력 ≈ Δ의 57.7%",
    example: {
      question:
        "단상 변압기 1대 용량 100 kVA를 V결선했을 때 3상 출력은?",
      solution: [
        "V결선 3상 출력 $= \\sqrt{3} \\times (\\text{1대 용량})$",
        "$= 1.732 \\times 100 \\approx 173\\ \\text{kVA}$",
        "(변압기 2대 합 200 kVA 대비 이용률 약 86.6%)",
      ],
      answer: "약 173 kVA",
    },
  },
];
