import type { Flashcard } from "../types";

/**
 * 전기기기 확장 카드. topic은 chapters.ts CHAPTERS.전기기기 의 8챕터 중 하나:
 * 직류기 / 변압기 / 유도전동기 / 동기기 / 정류·전력변환 / 제어기기 /
 * 특수기기 / 시험·정격.  id 접두사: m-
 */
export const machineCards: Flashcard[] = [
  // ──────────────────────────────────────────────────────────
  // 직류기
  // ──────────────────────────────────────────────────────────
  {
    id: "m-dc-emf-machine",
    front: "직류기 유기 기전력 $E$ 공식?",
    back: "$E = \\dfrac{P \\cdot Z \\cdot \\phi \\cdot N}{60 \\cdot a}$\n$P$ 극수, $Z$ 총 도체수, $\\phi$ 극당 자속[Wb], $N$ 회전수[rpm], $a$ 병렬회로수\n→ $E \\propto \\phi N$",
    subject: "전기기기",
    topic: "직류기",
    source: "preset",
    hint: "극수·도체수·자속·회전수에 비례, 병렬회로수에 반비례",
    example: {
      question: "$P=4$, $Z=400$, $\\phi=0.02$ Wb, $N=1500$ rpm, 파권($a=2$)일 때 $E$는?",
      solution: [
        "$E = \\dfrac{4 \\times 400 \\times 0.02 \\times 1500}{60 \\times 2}$",
        "$= \\dfrac{48000}{120} = 400$ V",
      ],
      answer: "$E = 400\\ \\text{V}$",
    },
  },
  {
    id: "m-dc-winding",
    front: "직류기 중권(병렬권)과 파권(직렬권)의 병렬회로수 $a$?",
    back: "중권(lap): $a = P$ (극수와 같음), 저전압·대전류용\n파권(wave): $a = 2$ (극수 무관), 고전압·소전류용\n중권은 균압환이 필요할 수 있음",
    subject: "전기기기",
    topic: "직류기",
    source: "preset",
    hint: "중권 a=P, 파권 a=2",
  },
  {
    id: "m-dc-armature-reaction",
    front: "직류기 전기자 반작용의 영향과 대책?",
    back: "영향: ① 주자속 감소(감자작용) ② 전기적 중성축 이동 ③ 정류 불량(불꽃)\n대책: ① 보극(전압정류) ② 보상권선 ③ 브러시를 중성축으로 이동",
    subject: "전기기기",
    topic: "직류기",
    source: "preset",
    hint: "감자·중성축 이동·정류불량 → 보극·보상권선",
  },
  {
    id: "m-dc-commutation",
    front: "직류기 양호한 정류를 위한 방법?",
    back: "① 보극 설치(전압정류, 가장 효과적)\n② 브러시 접촉저항 증가(탄소 브러시, 저항정류)\n③ 정류주기를 길게(리액턴스 전압 ↓)\n리액턴스 전압 $e_L = L\\dfrac{2I_c}{T_c}$ 를 작게",
    subject: "전기기기",
    topic: "직류기",
    source: "preset",
    hint: "보극·탄소브러시·정류주기 ↑",
  },
  {
    id: "m-dc-shunt-motor",
    front: "직류 분권전동기의 속도·토크 특성?",
    back: "속도 $N = K\\dfrac{V - I_a R_a}{\\phi}$ → 부하 변해도 속도 거의 일정(정속도 특성)\n토크 $T \\propto \\phi I_a \\propto I_a$ (계자전류 일정)\n계자회로 단선 시 위험속도(무구속) 주의",
    subject: "전기기기",
    topic: "직류기",
    source: "preset",
    hint: "정속도 특성, 계자 단선 시 위험속도",
  },
  {
    id: "m-dc-series-motor",
    front: "직류 직권전동기의 특성과 주의점?",
    back: "$\\phi \\propto I_a$ 이므로 $T \\propto I_a^2$ → 큰 기동토크\n무부하 시 속도가 무한대로 상승(위험) → 벨트 운전 금지, 직결\n전동차·기중기·크레인에 사용",
    subject: "전기기기",
    topic: "직류기",
    source: "preset",
    hint: "T∝Ia², 무부하 위험, 전동차용",
  },
  {
    id: "m-dc-speed-control",
    front: "직류전동기 속도제어 3가지 방법?",
    back: "① 계자제어: $\\phi$ 조정, 정출력 제어, 효율 좋음\n② 저항제어: 전기자 직렬저항, 손실 큼, 효율 나쁨\n③ 전압제어: 공급전압 조정, 정토크, 워드레오나드/정지레오나드 방식",
    subject: "전기기기",
    topic: "직류기",
    source: "preset",
    hint: "계자·저항·전압 제어",
  },
  {
    id: "m-dc-braking",
    front: "직류전동기의 제동(전기제동) 3가지?",
    back: "① 발전제동: 발생 전력을 저항으로 소비(열)\n② 회생제동: 발생 전력을 전원으로 반환\n③ 역전(플러깅)제동: 전기자 전류 방향을 반대로, 급제동",
    subject: "전기기기",
    topic: "직류기",
    source: "preset",
    hint: "발전·회생·역전(플러깅)",
  },
  {
    id: "m-dc-starting",
    front: "직류전동기 기동 시 기동저항을 넣는 이유?",
    back: "기동 순간 $N=0$ → 역기전력 $E=0$ → $I_a = \\dfrac{V}{R_a}$ 로 과대(정격의 수십 배)\n기동저항 $R_s$ 직렬로 $I_a = \\dfrac{V}{R_a + R_s}$ 제한, 속도 상승하면 단계적으로 단락",
    subject: "전기기기",
    topic: "직류기",
    source: "preset",
    hint: "기동 시 역기전력 0 → 과전류 방지",
    example: {
      question: "$V=200$ V, $R_a=0.5\\,\\Omega$. 기동전류를 40 A로 제한할 기동저항은?",
      solution: [
        "$R_a + R_s = \\dfrac{V}{I_a} = \\dfrac{200}{40} = 5\\,\\Omega$",
        "$R_s = 5 - 0.5 = 4.5\\,\\Omega$",
      ],
      answer: "$R_s = 4.5\\ \\Omega$",
    },
  },
  {
    id: "m-dc-generator-types",
    front: "직류 분권발전기와 직권발전기의 전압 특성 차이?",
    back: "분권발전기: 부하 증가 시 단자전압 점차 하강(수하 특성), 자기여자\n직권발전기: 부하 증가 시 전압 상승(무부하 시 발전 불가)\n타여자: 외부 전원으로 계자, 전압 조정 용이",
    subject: "전기기기",
    topic: "직류기",
    source: "preset",
    hint: "분권 하강, 직권 상승",
  },
  {
    id: "m-dc-torque-formula",
    front: "직류전동기 토크 $T$ 공식?",
    back: "$T = \\dfrac{P \\cdot Z \\cdot \\phi \\cdot I_a}{2\\pi a}$ [N·m]\n또는 $T = \\dfrac{60}{2\\pi}\\cdot\\dfrac{E I_a}{N} = 9.55\\dfrac{P_o}{N}$\n$T \\propto \\phi I_a$",
    subject: "전기기기",
    topic: "직류기",
    source: "preset",
    hint: "T = 9.55 · P/N",
    example: {
      question: "출력 $P_o = 3.7$ kW, $N = 1500$ rpm일 때 토크는?",
      solution: [
        "$T = 9.55 \\times \\dfrac{3700}{1500}$",
        "$\\approx 23.6$ N·m",
      ],
      answer: "$T \\approx 23.6\\ \\text{N·m}$",
    },
  },
  {
    id: "m-dc-efficiency-condition",
    front: "직류기 최대 효율 조건?",
    back: "고정손(철손·기계손)과 가변손(동손)이 같을 때 최대 효율\n$P_i$(고정손) $= I^2 R$(가변손)\n부하가 줄면 가변손이 줄어 최대효율점이 정격 이하에서 발생",
    subject: "전기기기",
    topic: "직류기",
    source: "preset",
    hint: "고정손 = 가변손",
  },

  // ──────────────────────────────────────────────────────────
  // 변압기
  // ──────────────────────────────────────────────────────────
  {
    id: "m-trans-emf-formula",
    front: "변압기 유기 기전력 공식?",
    back: "$E = 4.44 \\, f \\, N \\, \\phi_m$ [V]\n$f$ 주파수, $N$ 권수, $\\phi_m$ 최대 자속[Wb]\n$\\phi_m = B_m \\times A$ (자속밀도 × 철심 단면적)",
    subject: "전기기기",
    topic: "변압기",
    source: "preset",
    hint: "E = 4.44 f N Φm",
    example: {
      question: "$f=60$ Hz, $N=200$회, $\\phi_m = 0.01$ Wb일 때 기전력은?",
      solution: [
        "$E = 4.44 \\times 60 \\times 200 \\times 0.01$",
        "$= 532.8$ V",
      ],
      answer: "$E \\approx 533\\ \\text{V}$",
    },
  },
  {
    id: "m-trans-equivalent",
    front: "변압기 등가회로에서 여자전류의 두 성분?",
    back: "여자전류 $I_0 = I_i + I_\\phi$\n① 철손전류 $I_i$: 철손 담당, 여자 컨덕턴스 $g_0$\n② 자화전류 $I_\\phi$: 자속 생성, 여자 서셉턴스 $b_0$\n$I_0 = \\sqrt{I_i^2 + I_\\phi^2}$",
    subject: "전기기기",
    topic: "변압기",
    source: "preset",
    hint: "철손전류 + 자화전류",
  },
  {
    id: "m-trans-voltage-regulation",
    front: "변압기 전압변동률 $\\varepsilon$ 공식?",
    back: "$\\varepsilon = \\dfrac{V_{20} - V_{2n}}{V_{2n}} \\times 100\\,[\\%]$\n근사식: $\\varepsilon \\approx p\\cos\\theta + q\\sin\\theta$\n$p$ %저항강하, $q$ %리액턴스강하 (지상부하 +, 진상 −)",
    subject: "전기기기",
    topic: "변압기",
    source: "preset",
    hint: "ε ≈ p cosθ + q sinθ",
    example: {
      question: "$p=2\\%$, $q=4\\%$, 역률 0.8(지상)일 때 전압변동률은?",
      solution: [
        "$\\sin\\theta = 0.6$",
        "$\\varepsilon \\approx 2 \\times 0.8 + 4 \\times 0.6 = 1.6 + 2.4$",
      ],
      answer: "$\\varepsilon \\approx 4\\,\\%$",
    },
  },
  {
    id: "m-trans-percent-impedance",
    front: "변압기 %임피던스와 단락전류의 관계?",
    back: "$\\%Z = \\dfrac{I_n Z}{V_n}\\times100$\n단락전류 $I_s = \\dfrac{100}{\\%Z}\\times I_n$\n%Z가 작을수록 단락전류가 커짐",
    subject: "전기기기",
    topic: "변압기",
    source: "preset",
    hint: "Is = (100/%Z) · In",
    example: {
      question: "%Z = 4 %, 정격전류 100 A일 때 단락전류는?",
      solution: [
        "$I_s = \\dfrac{100}{4}\\times100$",
        "$= 25 \\times 100 = 2500$ A",
      ],
      answer: "$I_s = 2500\\ \\text{A}$",
    },
  },
  {
    id: "m-trans-parallel",
    front: "변압기 병렬운전 조건?",
    back: "① 극성이 같을 것\n② 권수비(변압비)가 같을 것\n③ %임피던스가 같을 것\n④ 내부 저항/리액턴스 비가 같을 것\n3상: 상회전 방향·위상변위(결선군) 일치",
    subject: "전기기기",
    topic: "변압기",
    source: "preset",
    hint: "극성·변압비·%Z·R:X 비",
  },
  {
    id: "m-trans-polarity",
    front: "변압기 가극성과 감극성의 차이?",
    back: "감극성(표준): 1·2차 유도전압이 서로 빼지는 방향, $V = V_1 - V_2$\n가극성: 더해지는 방향, $V = V_1 + V_2$\n우리나라 표준은 감극성",
    subject: "전기기기",
    topic: "변압기",
    source: "preset",
    hint: "표준은 감극성(빼짐)",
  },
  {
    id: "m-trans-3phase-connection",
    front: "변압기 Δ-Y 결선의 특징과 용도?",
    back: "Δ-Y: 2차에 중성점 접지 가능, 승압용(송전단)\n선간전압이 $\\sqrt{3}$배·30° 위상변위 발생\nY-Δ: 강압용(수전단), Δ가 제3고조파 순환로 제공",
    subject: "전기기기",
    topic: "변압기",
    source: "preset",
    hint: "Δ-Y 승압, Y-Δ 강압, 30° 변위",
  },
  {
    id: "m-trans-vv-connection",
    front: "변압기 V-V 결선의 출력과 이용률?",
    back: "Δ-Δ에서 1대 고장 시 V결선으로 3상 공급 가능\n출력비 = $\\dfrac{\\sqrt{3}}{3}$ ≈ 57.7 % (Δ-Δ 대비)\n이용률 = $\\dfrac{\\sqrt{3}}{2}$ ≈ 86.6 %",
    subject: "전기기기",
    topic: "변압기",
    source: "preset",
    hint: "출력 57.7%, 이용률 86.6%",
    example: {
      question: "단상 변압기 1대 용량 10 kVA를 V결선했을 때 3상 출력은?",
      solution: [
        "$P_V = \\sqrt{3}\\times P_1 = \\sqrt{3}\\times10$",
        "$\\approx 17.3$ kVA",
      ],
      answer: "$P_V \\approx 17.3\\ \\text{kVA}$",
    },
  },
  {
    id: "m-trans-autotransformer",
    front: "단권변압기의 장점과 특징?",
    back: "1·2차가 권선 일부 공통 → 동량·중량·손실 적고 효율 높음\n전압변동률 작음\n단점: 1·2차 절연이 곤란, 단락전류 큼\n자기용량 < 부하(선로)용량",
    subject: "전기기기",
    topic: "변압기",
    source: "preset",
    hint: "권선 공통 → 소형·고효율, 절연 곤란",
  },
  {
    id: "m-trans-oc-sc-test",
    front: "변압기 무부하시험과 단락시험으로 구하는 값?",
    back: "무부하(개방)시험: 철손, 여자전류, 여자어드미턴스\n단락(임피던스)시험: 동손(임피던스 와트), %임피던스, 전압변동률\n→ 두 시험으로 효율·전압변동률 산출",
    subject: "전기기기",
    topic: "변압기",
    source: "preset",
    hint: "무부하=철손, 단락=동손",
  },
  {
    id: "m-trans-cooling",
    front: "변압기 냉각방식 약호의 의미?",
    back: "ONAN: 유입자냉식(기름 자연순환 + 공기 자연)\nONAF: 유입풍냉식(송풍기)\nOFAF: 유입송유풍냉식(펌프+송풍기)\n앞 2자=내부 매체/순환, 뒤 2자=외부 매체/순환",
    subject: "전기기기",
    topic: "변압기",
    source: "preset",
    hint: "ONAN 자냉, ONAF 풍냉",
  },
  {
    id: "m-trans-protection",
    front: "변압기 내부고장 보호장치?",
    back: "① 부흐홀츠 계전기: 절연유 분해가스·유동 검출(주탱크-콘서베이터 사이)\n② 비율차동계전기: 1·2차 전류차로 내부고장 검출\n③ 충격압력계전기, 온도계전기",
    subject: "전기기기",
    topic: "변압기",
    source: "preset",
    hint: "부흐홀츠·비율차동계전기",
  },
  {
    id: "m-trans-insulating-oil",
    front: "변압기 절연유의 구비조건?",
    back: "① 절연내력이 클 것\n② 점도가 낮고 비열·열전도 클 것(냉각 양호)\n③ 인화점 높고 응고점 낮을 것\n④ 화학적으로 안정, 산화·석출물이 없을 것",
    subject: "전기기기",
    topic: "변압기",
    source: "preset",
    hint: "절연내력↑·점도↓·인화점↑",
  },
  {
    id: "m-trans-load-loss",
    front: "변압기 부하율 변동에 따른 동손 계산?",
    back: "동손은 부하전류의 제곱에 비례\n$P_c = \\left(\\dfrac{I}{I_n}\\right)^2 P_{cn} = (\\text{부하율})^2 \\times P_{cn}$\n철손은 부하에 무관(일정)",
    subject: "전기기기",
    topic: "변압기",
    source: "preset",
    hint: "동손 ∝ 부하율²",
    example: {
      question: "정격동손 200 W. 부하율 50 %일 때 동손은?",
      solution: [
        "$P_c = 0.5^2 \\times 200$",
        "$= 0.25 \\times 200 = 50$ W",
      ],
      answer: "$P_c = 50\\ \\text{W}$",
    },
  },
  {
    id: "m-trans-day-efficiency",
    front: "변압기 전일효율(일효율)의 정의?",
    back: "$\\eta_{day} = \\dfrac{\\text{1일 출력전력량}}{\\text{1일 출력전력량} + 24h\\,철손 + 부하시간 동손}\\times100$\n경부하 시간이 길면 철손이 작은 변압기가 유리",
    subject: "전기기기",
    topic: "변압기",
    source: "preset",
    hint: "하루 전력량 기준 효율",
  },

  // ──────────────────────────────────────────────────────────
  // 유도전동기
  // ──────────────────────────────────────────────────────────
  {
    id: "m-im-rotor-speed",
    front: "유도전동기 회전자속도 $N$ 공식?",
    back: "$N = (1 - s) N_s = (1-s)\\dfrac{120 f}{P}$ [rpm]\n슬립 $s$가 클수록 회전자속도 낮음\n$s=0$이면 동기속도, $s=1$이면 정지(기동)",
    subject: "전기기기",
    topic: "유도전동기",
    source: "preset",
    hint: "N = (1−s)Ns",
    example: {
      question: "60 Hz, 4극, 슬립 5 %일 때 회전속도는?",
      solution: [
        "$N_s = \\dfrac{120\\times60}{4} = 1800$ rpm",
        "$N = (1-0.05)\\times1800 = 1710$ rpm",
      ],
      answer: "$N = 1710\\ \\text{rpm}$",
    },
  },
  {
    id: "m-im-power-flow",
    front: "유도전동기 2차 입력·동손·기계출력의 비?",
    back: "$P_2 : P_{c2} : P_o = 1 : s : (1-s)$\n$P_2$ 2차입력, $P_{c2}$ 2차동손, $P_o$ 기계적출력\n$P_{c2} = s P_2$, $P_o = (1-s)P_2$",
    subject: "전기기기",
    topic: "유도전동기",
    source: "preset",
    hint: "1 : s : (1−s)",
    example: {
      question: "2차입력 5 kW, 슬립 4 %일 때 기계적 출력은?",
      solution: [
        "$P_o = (1-s)P_2 = 0.96\\times5$",
        "$= 4.8$ kW",
      ],
      answer: "$P_o = 4.8\\ \\text{kW}$",
    },
  },
  {
    id: "m-im-secondary-efficiency",
    front: "유도전동기 2차 효율 공식?",
    back: "$\\eta_2 = \\dfrac{P_o}{P_2} = 1 - s = \\dfrac{N}{N_s}$\n슬립이 작을수록 2차효율이 높음",
    subject: "전기기기",
    topic: "유도전동기",
    source: "preset",
    hint: "η₂ = 1 − s = N/Ns",
  },
  {
    id: "m-im-starting-cage",
    front: "농형 유도전동기 기동법 4가지?",
    back: "① 전전압(직입)기동: 5.5 kW 이하 소형\n② Y-Δ 기동: 기동전류·토크 1/3\n③ 기동보상기(단권변압기)법\n④ 리액터 기동\n*리플전동기/소프트스타터도 사용",
    subject: "전기기기",
    topic: "유도전동기",
    source: "preset",
    hint: "직입·Y-Δ·기동보상기·리액터",
  },
  {
    id: "m-im-ystart",
    front: "Y-Δ 기동 시 기동전류·기동토크가 1/3이 되는 이유?",
    back: "Y결선 시 상전압이 $\\dfrac{1}{\\sqrt3}$배 → 상전류 $\\dfrac{1}{\\sqrt3}$, 선전류는 직입의 $\\dfrac{1}{3}$\n토크는 전압의 제곱에 비례하므로 $\\left(\\dfrac{1}{\\sqrt3}\\right)^2 = \\dfrac{1}{3}$",
    subject: "전기기기",
    topic: "유도전동기",
    source: "preset",
    hint: "전압 1/√3 → 전류·토크 1/3",
  },
  {
    id: "m-im-wound-starting",
    front: "권선형 유도전동기의 기동법?",
    back: "2차 저항기동(기동저항기)법: 슬립링을 통해 외부저항 삽입\n비례추이 원리로 기동전류 ↓, 기동토크 ↑\n속도 상승하면 저항을 단계적으로 단락",
    subject: "전기기기",
    topic: "유도전동기",
    source: "preset",
    hint: "2차 외부저항(비례추이)",
  },
  {
    id: "m-im-speed-control",
    front: "유도전동기 속도제어 방법?",
    back: "① 주파수제어(VVVF 인버터): 가장 광범위, $N_s\\propto f$\n② 극수변환: 단계적\n③ 2차 저항제어(권선형)\n④ 2차 여자법(슬립 전력 회수)\n⑤ 전압제어",
    subject: "전기기기",
    topic: "유도전동기",
    source: "preset",
    hint: "주파수·극수·2차저항·2차여자",
  },
  {
    id: "m-im-vf-constant",
    front: "유도전동기 인버터 제어에서 V/f 일정 제어를 하는 이유?",
    back: "$E = 4.44 f N \\phi_m$ → 주파수 낮추며 전압 그대로면 자속 과대(자기포화·과열)\n$V/f$ 를 일정하게 유지하면 자속 일정 → 토크 일정 유지",
    subject: "전기기기",
    topic: "유도전동기",
    source: "preset",
    hint: "자속 일정 유지 → 토크 일정",
  },
  {
    id: "m-im-no-load-test",
    front: "유도전동기 무부하시험·구속시험으로 알 수 있는 것?",
    back: "무부하시험: 철손 + 기계손, 여자전류, 여자어드미턴스\n구속(정지)시험: 동손, 누설임피던스, 기동특성\n→ 등가회로 정수 산출",
    subject: "전기기기",
    topic: "유도전동기",
    source: "preset",
    hint: "무부하=철·기계손, 구속=동손",
  },
  {
    id: "m-im-frequency-effect",
    front: "유도전동기에 정격보다 낮은 주파수를 가하면?",
    back: "동기속도 $N_s = \\dfrac{120f}{P}$ 감소 → 속도 감소\n전압 일정 시 자속 증가 → 여자전류·철손 증가, 과열 위험\n그래서 V/f 일정 제어 필요",
    subject: "전기기기",
    topic: "유도전동기",
    source: "preset",
    hint: "속도↓, 자속↑(과열)",
  },
  {
    id: "m-im-crawling",
    front: "유도전동기 크롤링(차동기 운전) 현상?",
    back: "고조파 자속에 의해 동기속도의 1/7 등 낮은 속도에서 안정 운전에 머무는 현상\n원인: 공극 자속의 고조파(슬롯 고조파)\n대책: 사구(skew slot), 적절한 슬롯수 선정",
    subject: "전기기기",
    topic: "유도전동기",
    source: "preset",
    hint: "고조파로 저속 고착 → 사구",
  },
  {
    id: "m-im-cogging",
    front: "유도전동기 코깅(자기 고착) 현상과 대책?",
    back: "고정자·회전자 슬롯수가 같거나 정수배일 때 회전자가 슬롯에 자기적으로 끌려 기동 못하는 현상\n대책: 회전자 슬롯을 비스듬히(사구), 슬롯수를 다르게 설계",
    subject: "전기기기",
    topic: "유도전동기",
    source: "preset",
    hint: "슬롯수 정수배 → 기동불능, 사구 대책",
  },
  {
    id: "m-im-power-factor",
    front: "유도전동기의 역률이 낮은 이유와 개선?",
    back: "공극을 통한 자화전류(무효분)가 커서 지상 역률\n경부하 시 역률이 더 낮음\n개선: 진상 콘덴서 병렬, 동기조상기, 적정 용량 선정",
    subject: "전기기기",
    topic: "유도전동기",
    source: "preset",
    hint: "자화전류로 지상, 콘덴서로 개선",
  },

  // ──────────────────────────────────────────────────────────
  // 동기기
  // ──────────────────────────────────────────────────────────
  {
    id: "m-sync-emf",
    front: "동기발전기 유기 기전력 공식?",
    back: "$E = 4.44 \\, k_w \\, f \\, N \\, \\phi$ [V]\n$k_w$ 권선계수(=분포계수×단절계수), $f$ 주파수, $N$ 직렬권수, $\\phi$ 극당 자속",
    subject: "전기기기",
    topic: "동기기",
    source: "preset",
    hint: "E = 4.44 kw f N Φ",
  },
  {
    id: "m-sync-frequency",
    front: "동기발전기 주파수와 극수·회전수 관계?",
    back: "$f = \\dfrac{P \\cdot N_s}{120}$ [Hz]\n극수가 많을수록 같은 주파수에 낮은 회전수\n수차발전기(저속·다극), 터빈발전기(고속·2극)",
    subject: "전기기기",
    topic: "동기기",
    source: "preset",
    hint: "f = P·Ns / 120",
    example: {
      question: "12극 발전기로 60 Hz를 만들려면 회전수는?",
      solution: [
        "$N_s = \\dfrac{120 f}{P} = \\dfrac{120\\times60}{12}$",
        "$= 600$ rpm",
      ],
      answer: "$N_s = 600\\ \\text{rpm}$",
    },
  },
  {
    id: "m-sync-distribution-factor",
    front: "동기기 분포권·단절권을 쓰는 이유?",
    back: "분포권: 권선을 여러 슬롯에 분산 → 고조파 감소, 파형 개선, 열 분산\n단절권: 코일 간격을 극간격보다 짧게 → 특정 고조파 제거, 동량 절감\n대신 기본파 기전력은 약간 감소(권선계수<1)",
    subject: "전기기기",
    topic: "동기기",
    source: "preset",
    hint: "고조파 감소·파형 개선",
  },
  {
    id: "m-sync-armature-reaction",
    front: "동기발전기 전기자 반작용(부하 역률별)?",
    back: "저항부하(동상): 교차자화작용\n지상(유도성): 감자작용 → 단자전압 하강\n진상(용량성): 증자작용 → 단자전압 상승",
    subject: "전기기기",
    topic: "동기기",
    source: "preset",
    hint: "지상=감자, 진상=증자",
  },
  {
    id: "m-sync-short-ratio",
    front: "동기기 단락비(SCR)의 의미?",
    back: "$K_s = \\dfrac{\\text{무부하 정격전압 계자전류}}{\\text{3상 단락 정격전류 계자전류}} = \\dfrac{1}{\\%Z}\\times100$\n단락비 큰 기계(철기계): 전압변동 작고 안정도 높음, 효율 약간 낮고 중량·가격 큼",
    subject: "전기기기",
    topic: "동기기",
    source: "preset",
    hint: "Ks = 100/%Z, 클수록 안정",
  },
  {
    id: "m-sync-parallel-condition",
    front: "동기발전기 병렬운전 조건?",
    back: "① 기전력 크기가 같을 것\n② 기전력 위상이 같을 것\n③ 기전력 주파수가 같을 것\n④ 기전력 파형이 같을 것\n(3상은 상회전 방향도 일치)",
    subject: "전기기기",
    topic: "동기기",
    source: "preset",
    hint: "크기·위상·주파수·파형",
  },
  {
    id: "m-sync-hunting",
    front: "동기기 난조(hunting)의 원인과 방지법?",
    back: "원인: 부하 급변, 조속기 감도 과민 → 회전자가 동기속도 부근에서 진동\n방지: 제동권선 설치(가장 효과적), 플라이휠로 관성 증대, 조속기 적정 조정",
    subject: "전기기기",
    topic: "동기기",
    source: "preset",
    hint: "제동권선으로 방지",
  },
  {
    id: "m-sync-condenser",
    front: "동기조상기의 역할(계자전류 조정)?",
    back: "무부하 동기전동기. 계자전류 조정으로 무효전력 연속 조정\n과여자 → 진상(콘덴서처럼, 역률 개선)\n부족여자 → 지상(리액터처럼)\n→ 전압·역률 조정 (V곡선)",
    subject: "전기기기",
    topic: "동기기",
    source: "preset",
    hint: "과여자=진상, 부족여자=지상",
  },
  {
    id: "m-sync-v-curve",
    front: "동기전동기 위상특성곡선(V곡선)이란?",
    back: "계자전류($I_f$) - 전기자전류($I_a$) 관계 곡선(V자 형태)\n최저점이 역률 1\n오른쪽(과여자)=진상, 왼쪽(부족여자)=지상\n부하가 클수록 곡선이 위로 이동",
    subject: "전기기기",
    topic: "동기기",
    source: "preset",
    hint: "If-Ia V자 곡선, 최저점 역률 1",
  },
  {
    id: "m-sync-motor-features",
    front: "동기전동기의 장단점?",
    back: "장점: 속도 일정(동기속도), 역률 조정 가능(1.0/진상), 효율 좋음\n단점: 기동토크 0(자기동 불가, 별도 기동법 필요), 난조 발생, 구조 복잡·가격 높음",
    subject: "전기기기",
    topic: "동기기",
    source: "preset",
    hint: "정속·역률조정 / 기동 곤란",
  },
  {
    id: "m-sync-starting",
    front: "동기전동기의 기동법?",
    back: "① 자기기동법: 제동권선을 이용해 유도전동기처럼 기동 후 동기 인입\n② 기동전동기법: 별도 유도/직류 전동기로 가속 후 동기\n기동 시 계자권선은 단락(고전압 방지)",
    subject: "전기기기",
    topic: "동기기",
    source: "preset",
    hint: "자기기동(제동권선)·기동전동기",
  },
  {
    id: "m-sync-power-angle",
    front: "동기기 부하각 $\\delta$와 안정도?",
    back: "출력 $P = \\dfrac{EV}{X_s}\\sin\\delta$, $\\delta=90°$에서 최대(안정한계)\n정상운전은 $\\delta < 90°$ 영역\n단락비를 크게/리액턴스를 작게 하면 안정도 향상",
    subject: "전기기기",
    topic: "동기기",
    source: "preset",
    hint: "δ=90°가 안정한계",
  },

  // ──────────────────────────────────────────────────────────
  // 정류·전력변환
  // ──────────────────────────────────────────────────────────
  {
    id: "m-conv-3phase-half",
    front: "3상 반파 정류회로의 직류 평균전압?",
    back: "$V_{dc} = 1.17 \\, V$ ($V$=상전압 실효값)\n맥동주파수 = 전원주파수의 3배\n맥동률 약 17 %로 단상보다 우수",
    subject: "전기기기",
    topic: "정류·전력변환",
    source: "preset",
    hint: "Vdc ≈ 1.17 V",
  },
  {
    id: "m-conv-3phase-full",
    front: "3상 전파(브리지) 정류회로의 직류 전압?",
    back: "$V_{dc} = 1.35 \\, V_L$ ($V_L$ 선간전압 실효값) $\\approx 2.34\\,V_{ph}$\n맥동주파수 = 전원의 6배, 맥동률 약 4 %로 매우 평탄\n대전력 정류에 표준",
    subject: "전기기기",
    topic: "정류·전력변환",
    source: "preset",
    hint: "Vdc ≈ 1.35 VL, 맥동 6배",
  },
  {
    id: "m-conv-ripple-factor",
    front: "맥동률(리플률)의 정의와 정류방식별 값?",
    back: "$\\gamma = \\dfrac{\\text{교류분 실효값}}{\\text{직류분}}\\times100$\n단상 반파 121 %, 단상 전파 48 %, 3상 반파 17 %, 3상 전파 4 %\n맥동률 작을수록 평활도 좋음",
    subject: "전기기기",
    topic: "정류·전력변환",
    source: "preset",
    hint: "반파 121, 전파 48, 3상전파 4 %",
  },
  {
    id: "m-conv-scr-firing",
    front: "SCR 위상제어에서 점호각 $\\alpha$와 출력전압?",
    back: "단상 전파(저항부하): $V_{dc} = \\dfrac{V_m}{\\pi}(1+\\cos\\alpha)$\n점호각 $\\alpha$를 키우면 출력전압 감소\n$\\alpha=0$이면 다이오드 정류와 동일(최대)",
    subject: "전기기기",
    topic: "정류·전력변환",
    source: "preset",
    hint: "α 클수록 출력 ↓",
  },
  {
    id: "m-conv-inverter",
    front: "인버터와 컨버터의 차이?",
    back: "컨버터(정류기): 교류 → 직류 (AC→DC)\n인버터: 직류 → 교류 (DC→AC)\n사이클로컨버터: 교류 → 다른 주파수 교류 (직접 AC→AC)\n초퍼: 직류 → 다른 크기 직류 (DC→DC)",
    subject: "전기기기",
    topic: "정류·전력변환",
    source: "preset",
    hint: "인버터 DC→AC, 컨버터 AC→DC",
  },
  {
    id: "m-conv-chopper",
    front: "직류 초퍼(DC 초퍼)의 동작 원리?",
    back: "스위칭소자를 고속 ON/OFF, 듀티비 $D$로 평균 출력전압 조정\n강압형: $V_o = D\\,V_s$\nPWM 제어로 직류 전압을 가변, 전기차·DC 모터 속도제어에 사용",
    subject: "전기기기",
    topic: "정류·전력변환",
    source: "preset",
    hint: "Vo = D·Vs (강압형)",
    example: {
      question: "입력 200 V, 듀티비 0.6인 강압 초퍼의 출력전압은?",
      solution: [
        "$V_o = D \\times V_s = 0.6\\times200$",
        "$= 120$ V",
      ],
      answer: "$V_o = 120\\ \\text{V}$",
    },
  },
  {
    id: "m-conv-diac-triac",
    front: "DIAC와 TRIAC의 특징?",
    back: "DIAC: 양방향 2단자, 브레이크오버 전압에서 도통, TRIAC 트리거용\nTRIAC: 양방향 3단자, 교류 양·음 반주기 모두 제어 가능\n→ 조광기, 속도제어 등 교류 위상제어",
    subject: "전기기기",
    topic: "정류·전력변환",
    source: "preset",
    hint: "TRIAC 양방향 교류제어",
  },
  {
    id: "m-conv-gto",
    front: "GTO(Gate Turn-Off 사이리스터)의 특징?",
    back: "SCR과 달리 게이트 신호(역방향)로 직접 OFF 가능\n자기소호 소자 → 강제전류차단 회로 불필요\n대전력 인버터·초퍼에 사용",
    subject: "전기기기",
    topic: "정류·전력변환",
    source: "preset",
    hint: "게이트로 소호 가능한 SCR",
  },
  {
    id: "m-conv-freewheeling",
    front: "환류 다이오드(프리휠링 다이오드)의 역할?",
    back: "유도성 부하 정류 시 스위치 OFF 순간 인덕터 전류의 통로 제공\n역기전력에 의한 소자 파괴 방지, 출력전압 음(−) 방지로 평활 개선",
    subject: "전기기기",
    topic: "정류·전력변환",
    source: "preset",
    hint: "인덕터 전류 환류로 소자 보호",
  },
  {
    id: "m-conv-pwm",
    front: "PWM(펄스폭 변조) 제어의 원리?",
    back: "일정 주파수 펄스의 폭(듀티)을 조절해 평균 전압·전류 제어\n인버터에서 정현파 기준과 삼각파 비교(SPWM)로 출력파형 형성\n고조파를 고주파 영역으로 밀어내 필터링 용이",
    subject: "전기기기",
    topic: "정류·전력변환",
    source: "preset",
    hint: "펄스폭으로 평균전압 조절",
  },

  // ──────────────────────────────────────────────────────────
  // 제어기기
  // ──────────────────────────────────────────────────────────
  {
    id: "m-ctrl-mc-relay",
    front: "전자접촉기(MC)와 전자계전기(릴레이)의 차이?",
    back: "전자접촉기(MC): 주회로 대전류 개폐, 모터 등 부하 직접 제어\n전자계전기(릴레이): 제어회로 소전류 신호 처리\n둘 다 코일 여자 → 접점 동작",
    subject: "전기기기",
    topic: "제어기기",
    source: "preset",
    hint: "MC 주회로, 릴레이 제어회로",
  },
  {
    id: "m-ctrl-thermal-relay",
    front: "열동계전기(THR/EOCR)의 역할?",
    back: "전동기 과부하·과전류 시 발생열로 바이메탈을 변형시켜 접점 동작 → 회로 차단\nMC와 조합해 전자개폐기 구성, 과부하 보호 담당\nEOCR은 전자식 과전류 계전기",
    subject: "전기기기",
    topic: "제어기기",
    source: "preset",
    hint: "전동기 과부하 보호(바이메탈)",
  },
  {
    id: "m-ctrl-self-hold",
    front: "자기유지회로(자기보지)의 구성 원리?",
    back: "기동(PB-ON) 누름 → MC 여자 → MC의 a접점이 기동버튼과 병렬로 회로 유지\n정지(PB-OFF, b접점)를 누르면 회로 차단되어 정지\n순간 누름 신호를 연속 동작으로 유지",
    subject: "전기기기",
    topic: "제어기기",
    source: "preset",
    hint: "보조 a접점 병렬로 회로 유지",
  },
  {
    id: "m-ctrl-interlock",
    front: "인터록(선행동작 우선) 회로의 목적?",
    back: "정·역 운전 등에서 두 동작이 동시에 일어나지 못하게 함\n상대 MC의 b접점을 자기 회로에 직렬 삽입 → 한쪽 동작 시 다른 쪽 차단\n정역전 동시투입에 의한 단락사고 방지",
    subject: "전기기기",
    topic: "제어기기",
    source: "preset",
    hint: "동시동작 방지(상대 b접점)",
  },
  {
    id: "m-ctrl-timer",
    front: "한시계전기(타이머)의 한시동작·한시복귀?",
    back: "한시동작 순시복귀(On-delay): 입력 후 설정시간 뒤 동작, 차단 즉시 복귀\n순시동작 한시복귀(Off-delay): 입력 즉시 동작, 차단 후 설정시간 뒤 복귀\nTLR로 순차제어 구성",
    subject: "전기기기",
    topic: "제어기기",
    source: "preset",
    hint: "On-delay / Off-delay",
  },
  {
    id: "m-ctrl-contact-symbol",
    front: "a접점·b접점·c접점의 차이?",
    back: "a접점(NO, 메이크): 평상시 열림, 동작 시 닫힘\nb접점(NC, 브레이크): 평상시 닫힘, 동작 시 열림\nc접점(전환): a+b 공통, 절환 동작",
    subject: "전기기기",
    topic: "제어기기",
    source: "preset",
    hint: "a=NO, b=NC, c=전환",
  },
  {
    id: "m-ctrl-limit-switch",
    front: "리미트 스위치와 근접 스위치의 차이?",
    back: "리미트 스위치: 물체가 기계적으로 레버를 눌러 접점 동작(접촉식)\n근접 스위치: 자기·정전용량 변화로 비접촉 검출(무접점, 마모 없음, 고속)\n위치·이송 끝단 검출에 사용",
    subject: "전기기기",
    topic: "제어기기",
    source: "preset",
    hint: "접촉식 vs 비접촉식",
  },
  {
    id: "m-ctrl-feedback",
    front: "개루프 제어와 폐루프(피드백) 제어의 차이?",
    back: "개루프: 출력을 입력에 되먹임 안 함, 단순·저가, 외란에 약함\n폐루프: 출력을 검출해 목표와 비교·보정, 정확·안정, 구조 복잡\n자동제어의 기본은 폐루프(피드백) 제어",
    subject: "전기기기",
    topic: "제어기기",
    source: "preset",
    hint: "되먹임 유무",
  },
  {
    id: "m-ctrl-sequence",
    front: "시퀀스 제어의 정의와 예?",
    back: "미리 정한 순서에 따라 각 단계를 차례로 진행하는 제어\n조건(시간·신호) 충족 시 다음 단계로 이행\n예: 전동기 Y-Δ 기동, 신호등, 자동문, 컨베이어 순차기동",
    subject: "전기기기",
    topic: "제어기기",
    source: "preset",
    hint: "정해진 순서대로 진행",
  },
  {
    id: "m-ctrl-pid",
    front: "PID 제어 각 동작의 역할?",
    back: "P(비례): 편차에 비례한 조작, 잔류편차(오프셋) 존재\nI(적분): 잔류편차 제거(정상편차 0)\nD(미분): 변화율에 대응, 응답 빠르고 안정도 향상(오버슈트 억제)",
    subject: "전기기기",
    topic: "제어기기",
    source: "preset",
    hint: "P 비례, I 편차제거, D 속응성",
  },
  {
    id: "m-ctrl-plc",
    front: "PLC(프로그래머블 로직 컨트롤러)의 특징?",
    back: "릴레이 시퀀스를 프로그램(래더 다이어그램)으로 구현\n배선 변경 없이 프로그램 수정으로 제어 변경 용이\n신뢰성·내환경성 우수, 산업 자동화 표준 제어장치",
    subject: "전기기기",
    topic: "제어기기",
    source: "preset",
    hint: "프로그램형 시퀀스 제어기",
  },

  // ──────────────────────────────────────────────────────────
  // 특수기기
  // ──────────────────────────────────────────────────────────
  {
    id: "m-spec-servo-motor",
    front: "서보모터의 특징과 용도?",
    back: "위치·속도·토크를 정밀 제어하는 모터(엔코더 피드백)\n응답 빠르고 기동·정지·역전 빈번에 적합, 넓은 속도제어 범위\n로봇, CNC, 반도체 장비 위치결정에 사용",
    subject: "전기기기",
    topic: "특수기기",
    source: "preset",
    hint: "고응답 정밀 위치제어(엔코더)",
  },
  {
    id: "m-spec-universal-motor",
    front: "단상 직권(만능)전동기의 특징?",
    back: "교류·직류 모두 사용 가능(만능전동기)\n직권 특성으로 기동토크 크고 고속 회전 가능\n전기드릴·믹서·진공청소기 등 소형 가전에 사용",
    subject: "전기기기",
    topic: "특수기기",
    source: "preset",
    hint: "AC/DC 겸용, 고속·고토크",
  },
  {
    id: "m-spec-single-phase-im",
    front: "단상 유도전동기가 자기기동을 못하는 이유와 기동법?",
    back: "단상은 회전자계가 없어 기동토크 0(교번자계만)\n기동법(토크 큰 순): 반발기동형 > 콘덴서기동형 > 분상기동형 > 셰이딩코일형",
    subject: "전기기기",
    topic: "특수기기",
    source: "preset",
    hint: "회전자계 없음 → 별도 기동권선",
  },
  {
    id: "m-spec-capacitor-motor",
    front: "콘덴서 기동형 단상 유도전동기의 원리?",
    back: "기동권선에 콘덴서를 직렬로 → 주권선과 전류 위상차(약 90°) 발생 → 회전자계 형성\n역률·기동토크 양호, 가정용 펌프·에어컨에 널리 사용",
    subject: "전기기기",
    topic: "특수기기",
    source: "preset",
    hint: "콘덴서로 위상차 → 회전자계",
  },
  {
    id: "m-spec-shaded-pole",
    front: "셰이딩 코일형 단상 전동기의 특징?",
    back: "자극 일부에 단락 동링(셰이딩 코일)을 감아 이동자계 형성\n구조 간단·저가지만 기동토크 작고 효율 낮음, 역전 불가\n소형 선풍기·환풍기에 사용",
    subject: "전기기기",
    topic: "특수기기",
    source: "preset",
    hint: "셰이딩코일, 소형·저토크",
  },
  {
    id: "m-spec-reluctance-motor",
    front: "릴럭턴스(자기저항) 전동기의 원리?",
    back: "회전자에 영구자석·권선 없이 돌극(자기저항 차)으로 동기속도 운전\n자속이 자기저항이 최소가 되는 위치로 회전자를 끌어당김\n구조 간단·견고, 타이머·계측기에 사용",
    subject: "전기기기",
    topic: "특수기기",
    source: "preset",
    hint: "자기저항 최소 위치로 회전",
  },
  {
    id: "m-spec-hysteresis-motor",
    front: "히스테리시스 전동기의 특징?",
    back: "회전자의 히스테리시스 손실 토크로 회전, 동기속도 운전\n기동~동기 전 구간 일정 토크, 진동·소음 적음\n전축(턴테이블)·정밀 기기에 사용",
    subject: "전기기기",
    topic: "특수기기",
    source: "preset",
    hint: "히스테리시스 토크, 동기속도",
  },
  {
    id: "m-spec-linear-motor",
    front: "리니어(선형) 모터의 특징?",
    back: "회전형 모터를 직선으로 펼친 구조 → 직접 직선운동(회전→직선 변환기구 불필요)\n마찰 적고 고속·고정밀 위치결정\n자기부상열차, 반송장치에 사용",
    subject: "전기기기",
    topic: "특수기기",
    source: "preset",
    hint: "직선운동 직접 생성",
  },
  {
    id: "m-spec-srm",
    front: "SRM(스위치드 릴럭턴스 모터)의 특징?",
    back: "고정자·회전자 모두 돌극, 회전자에 권선·자석 없음\n구조 견고·저가, 고속운전 가능, 제어기(인버터) 필수\n토크 리플·소음이 단점",
    subject: "전기기기",
    topic: "특수기기",
    source: "preset",
    hint: "돌극형, 견고·고속, 제어기 필수",
  },
  {
    id: "m-spec-resolver",
    front: "리졸버와 엔코더(위치센서)의 차이?",
    back: "엔코더: 광학식 펄스로 위치/속도 검출, 고분해능, 환경에 다소 민감\n리졸버: 변압기 원리(아날로그), 내환경성·내진동 우수, 절대위치\n서보·로봇 피드백 소자",
    subject: "전기기기",
    topic: "특수기기",
    source: "preset",
    hint: "엔코더 광학, 리졸버 자기식",
  },
  {
    id: "m-spec-ac-servo",
    front: "AC 서보모터가 DC 서보모터보다 선호되는 이유?",
    back: "브러시·정류자가 없어 유지보수 불필요, 수명 길고 고속 가능\n방열 우수, 큰 출력에 유리\n현대 산업 서보는 대부분 AC(영구자석 동기형)",
    subject: "전기기기",
    topic: "특수기기",
    source: "preset",
    hint: "무브러시 → 무보수·고속",
  },

  // ──────────────────────────────────────────────────────────
  // 시험·정격
  // ──────────────────────────────────────────────────────────
  {
    id: "m-rate-3phase-power",
    front: "3상 전동기 입력전력 공식?",
    back: "$P = \\sqrt{3}\\, V_L \\, I_L \\cos\\theta$ [W]\n$V_L$ 선간전압, $I_L$ 선전류, $\\cos\\theta$ 역률\n출력 = 입력 × 효율",
    subject: "전기기기",
    topic: "시험·정격",
    source: "preset",
    hint: "P = √3 VL IL cosθ",
    example: {
      question: "380 V, 선전류 20 A, 역률 0.85인 3상 전동기 입력은?",
      solution: [
        "$P = \\sqrt3\\times380\\times20\\times0.85$",
        "$\\approx 1.732\\times380\\times17 \\approx 11{,}190$ W",
      ],
      answer: "$P \\approx 11.2\\ \\text{kW}$",
    },
  },
  {
    id: "m-rate-motor-current",
    front: "3상 전동기 정격(전부하)전류 계산?",
    back: "$I = \\dfrac{P}{\\sqrt3\\, V \\cos\\theta\\, \\eta}$ [A]\n$P$ 정격출력[W], $V$ 선간전압, $\\cos\\theta$ 역률, $\\eta$ 효율\n전선·차단기 용량 선정의 기준",
    subject: "전기기기",
    topic: "시험·정격",
    source: "preset",
    hint: "I = P / (√3·V·cosθ·η)",
    example: {
      question: "출력 3.7 kW, 380 V, 역률 0.8, 효율 0.85인 3상 전동기 전류는?",
      solution: [
        "$I = \\dfrac{3700}{\\sqrt3\\times380\\times0.8\\times0.85}$",
        "$\\approx \\dfrac{3700}{447.5} \\approx 8.3$ A",
      ],
      answer: "$I \\approx 8.3\\ \\text{A}$",
    },
  },
  {
    id: "m-rate-duty",
    front: "전동기 정격(사용)의 종류?",
    back: "연속정격(S1): 무한정 연속 운전 가능\n단시간정격(S2): 정해진 짧은 시간만 정격\n반복정격(S3): 운전·정지 주기 반복\n명판의 정격에 맞춰 선정",
    subject: "전기기기",
    topic: "시험·정격",
    source: "preset",
    hint: "연속/단시간/반복 정격",
  },
  {
    id: "m-rate-insulation-class",
    front: "절연물 종별 허용 최고온도?",
    back: "Y 90 / A 105 / E 120 / B 130 / F 155 / H 180 / C 180 초과\n절연 등급이 높을수록 허용온도 높음 (전동기·변압기 수명 좌우)",
    subject: "전기기기",
    topic: "시험·정격",
    source: "preset",
    hint: "Y90 A105 E120 B130 F155 H180",
  },
  {
    id: "m-rate-temp-rise-test",
    front: "온도상승시험의 목적과 방법?",
    back: "정격부하 운전 시 권선·철심 온도상승이 절연 허용한도 이내인지 확인\n측정법: 저항법(권선저항 변화로 평균온도), 온도계법, 매입온도계법\n절연 등급별 온도상승 한도 적용",
    subject: "전기기기",
    topic: "시험·정격",
    source: "preset",
    hint: "절연 한도 이내 확인(저항법)",
  },
  {
    id: "m-rate-withstand-test",
    front: "내전압(절연내력)시험이란?",
    back: "규정된 시험전압(상용주파)을 일정 시간(보통 1분) 인가해 절연이 견디는지 확인\n절연저항시험보다 가혹한 파괴 직전 검증\n변압기·기기 출고·정기점검 시 실시",
    subject: "전기기기",
    topic: "시험·정격",
    source: "preset",
    hint: "시험전압 1분 인가",
  },
  {
    id: "m-rate-efficiency-types",
    front: "발전기와 전동기의 규약효율 식 차이?",
    back: "발전기: $\\eta = \\dfrac{\\text{출력}}{\\text{출력}+\\text{손실}}\\times100$\n전동기: $\\eta = \\dfrac{\\text{입력}-\\text{손실}}{\\text{입력}}\\times100$\n출력 측정이 어려운 쪽을 손실로 계산",
    subject: "전기기기",
    topic: "시험·정격",
    source: "preset",
    hint: "발전기 출력기준, 전동기 입력기준",
  },
  {
    id: "m-rate-loss-types",
    front: "회전기 손실의 분류?",
    back: "① 고정손: 철손(히스테리시스+와전류), 기계손(마찰·풍손)\n② 가변손: 동손($I^2R$, 부하전류 제곱에 비례), 표유부하손\n최대효율은 고정손=가변손",
    subject: "전기기기",
    topic: "시험·정격",
    source: "preset",
    hint: "고정손(철·기계) / 가변손(동손)",
  },
  {
    id: "m-rate-eddy-hysteresis",
    front: "철손을 줄이는 방법(히스테리시스손·와전류손)?",
    back: "히스테리시스손 $\\propto f B^2$ → 규소강판 사용(B-H 면적 ↓)\n와전류손 $\\propto (f B t)^2$ → 얇은 강판 성층(절연) 사용\n→ 변압기·회전기 철심은 성층 규소강판",
    subject: "전기기기",
    topic: "시험·정격",
    source: "preset",
    hint: "규소강판 + 성층(얇게)",
  },
  {
    id: "m-rate-temp-resistance",
    front: "저항법에 의한 권선 온도상승 계산식?",
    back: "$t_2 = \\dfrac{R_2 - R_1}{R_1}(234.5 + t_1) + t_1$\n(구리, 0 ℃ 저항=0 인 온도 −234.5 ℃ 기준)\n$R_1,t_1$ 시험 전, $R_2$ 시험 후 저항",
    subject: "전기기기",
    topic: "시험·정격",
    source: "preset",
    hint: "구리: 234.5 상수 사용",
  },
  {
    id: "m-rate-nameplate",
    front: "전동기 명판(정격명판)의 주요 표시 항목?",
    back: "정격출력[kW], 정격전압[V], 정격전류[A], 정격주파수[Hz], 극수, 정격회전수[rpm], 역률, 효율, 정격(연속 등), 절연종별\n→ 전동기 선정·보호장치 정정의 기준",
    subject: "전기기기",
    topic: "시험·정격",
    source: "preset",
    hint: "출력·전압·전류·회전수·절연종별",
  },
];
