import type { Flashcard } from "../types";

/**
 * 전기이론 확장 카드. topic은 chapters.ts CHAPTERS.전기이론 의 8챕터 중 하나:
 * 직류회로 / 정전기 / 자기·자기회로 / 전자기 유도 / 교류회로 / 3상 교류 /
 * 비정현파 교류 / 회로망 정리.  id 접두사: t-
 */
export const theoryCards: Flashcard[] = [
  // ===== 직류회로 (11) =====
  {
    id: "t-resistivity",
    front: "도체의 저항과 고유저항(저항률)?",
    back: "$R = \\rho \\cdot \\dfrac{l}{A}$\n$\\rho$ 고유저항 [$\\Omega\\cdot\\text{m}$], $l$ 길이, $A$ 단면적.\n길이에 비례, 단면적에 반비례.",
    subject: "전기이론",
    topic: "직류회로",
    source: "preset",
    hint: "길이↑ 저항↑, 굵기↑ 저항↓",
    example: {
      question: "길이 200 m, 단면적 $2\\ \\text{mm}^2$, 고유저항 $1.7 \\times 10^{-8}\\ \\Omega\\cdot\\text{m}$인 동선의 저항은?",
      solution: [
        "$R = \\rho \\cdot \\dfrac{l}{A}$",
        "$A = 2\\ \\text{mm}^2 = 2 \\times 10^{-6}\\ \\text{m}^2$",
        "$R = 1.7 \\times 10^{-8} \\times \\dfrac{200}{2 \\times 10^{-6}}$",
        "$R = 1.7\\ \\Omega$",
      ],
      answer: "$R = 1.7\\ \\Omega$",
    },
  },
  {
    id: "t-temp-coefficient",
    front: "저항의 온도 변화 (구리)?",
    back: "$R_t = R_0 \\,[\\,1 + \\alpha_0 (t - t_0)\\,]$\n구리 20 ℃ 기준 $\\alpha \\approx 0.00393\\,/℃$.\n금속은 온도가 오르면 저항이 증가(정특성).",
    subject: "전기이론",
    topic: "직류회로",
    source: "preset",
    hint: "금속은 더우면 저항↑",
    example: {
      question: "20 ℃에서 $10\\ \\Omega$인 동선이 70 ℃가 되면 저항은? ($\\alpha = 0.004/℃$)",
      solution: [
        "$R_t = R_0 [1 + \\alpha(t - t_0)]$",
        "$R_t = 10 [1 + 0.004 \\times (70 - 20)]$",
        "$R_t = 10 (1 + 0.2) = 12\\ \\Omega$",
      ],
      answer: "$R_t = 12\\ \\Omega$",
    },
  },
  {
    id: "t-conductance",
    front: "컨덕턴스(G)와 병렬 합성?",
    back: "$G = \\dfrac{1}{R}$ [지멘스, S]\n병렬 회로에서는 컨덕턴스가 그대로 더해짐: $G = G_1 + G_2 + \\cdots$\n→ 병렬 합성 계산이 간단해짐.",
    subject: "전기이론",
    topic: "직류회로",
    source: "preset",
    hint: "저항의 역수, 병렬에서 덧셈",
    example: {
      question: "$5\\ \\Omega$, $10\\ \\Omega$, $10\\ \\Omega$ 병렬 회로의 합성저항을 컨덕턴스로 구하면?",
      solution: [
        "$G = \\dfrac{1}{5} + \\dfrac{1}{10} + \\dfrac{1}{10} = 0.2 + 0.1 + 0.1$",
        "$G = 0.4\\ \\text{S}$",
        "$R = \\dfrac{1}{G} = \\dfrac{1}{0.4} = 2.5\\ \\Omega$",
      ],
      answer: "$R = 2.5\\ \\Omega$",
    },
  },
  {
    id: "t-voltage-divider",
    front: "전압 분배 법칙 (직렬 2저항)?",
    back: "$V_1 = V \\cdot \\dfrac{R_1}{R_1 + R_2}$\n직렬에서는 큰 저항에 더 큰 전압이 걸린다.\n(전류 분배와 반대 — 분자에 '자기 자신'의 저항)",
    subject: "전기이론",
    topic: "직류회로",
    source: "preset",
    hint: "직렬: 분자에 자기 저항",
    example: {
      question: "12 V 전원에 $R_1 = 3\\ \\Omega$, $R_2 = 9\\ \\Omega$가 직렬일 때 $R_2$ 양단 전압은?",
      solution: [
        "$V_2 = V \\cdot \\dfrac{R_2}{R_1 + R_2}$",
        "$V_2 = 12 \\times \\dfrac{9}{3 + 9} = 12 \\times \\dfrac{9}{12}$",
        "$V_2 = 9\\ \\text{V}$",
      ],
      answer: "$V_2 = 9\\ \\text{V}$",
    },
  },
  {
    id: "t-emf-internal-r",
    front: "기전력·단자전압·내부저항?",
    back: "$V = E - I \\cdot r$\n$E$ 기전력, $r$ 전지 내부저항, $V$ 단자전압.\n전류가 흐르면 내부저항 전압강하만큼 단자전압이 떨어진다.",
    subject: "전기이론",
    topic: "직류회로",
    source: "preset",
    hint: "단자전압 = 기전력 - 내부강하",
    example: {
      question: "기전력 1.5 V, 내부저항 $0.5\\ \\Omega$인 전지에 $2.5\\ \\Omega$ 부하 연결 시 단자전압은?",
      solution: [
        "$I = \\dfrac{E}{r + R} = \\dfrac{1.5}{0.5 + 2.5} = 0.5\\ \\text{A}$",
        "$V = E - I r = 1.5 - 0.5 \\times 0.5$",
        "$V = 1.25\\ \\text{V}$",
      ],
      answer: "$V = 1.25\\ \\text{V}$",
    },
  },
  {
    id: "t-battery-series-parallel",
    front: "전지의 직렬·병렬 연결?",
    back: "직렬 $n$개: 기전력 $nE$, 내부저항 $nr$ (전압을 높일 때)\n병렬 $m$개: 기전력 $E$, 내부저항 $\\dfrac{r}{m}$ (전류 용량을 키울 때)",
    subject: "전기이론",
    topic: "직류회로",
    source: "preset",
    hint: "직렬=전압↑, 병렬=용량↑",
    example: {
      question: "기전력 2 V, 내부저항 $0.2\\ \\Omega$인 전지 3개를 직렬 연결하면 합성 기전력과 내부저항은?",
      solution: [
        "직렬: $E_{tot} = nE = 3 \\times 2 = 6\\ \\text{V}$",
        "$r_{tot} = nr = 3 \\times 0.2 = 0.6\\ \\Omega$",
      ],
      answer: "$E_{tot} = 6\\ \\text{V},\\ r_{tot} = 0.6\\ \\Omega$",
    },
  },
  {
    id: "t-joule-heat",
    front: "줄의 법칙(발열량)?",
    back: "$H = I^2 R t$ [J]\n칼로리 환산: $H = 0.24\\, I^2 R t$ [cal]\n전류의 제곱·저항·시간에 비례.",
    subject: "전기이론",
    topic: "직류회로",
    source: "preset",
    hint: "발열은 전류 제곱에 비례",
    example: {
      question: "$20\\ \\Omega$ 저항에 3 A가 10초 동안 흐를 때 발생 열량은 몇 J인가?",
      solution: [
        "$H = I^2 R t$",
        "$H = 3^2 \\times 20 \\times 10$",
        "$H = 9 \\times 20 \\times 10 = 1800\\ \\text{J}$",
      ],
      answer: "$H = 1800\\ \\text{J}$",
    },
  },
  {
    id: "t-electric-charge",
    front: "전하량과 전류의 관계?",
    back: "$Q = I \\cdot t$ [C]\n1 A = 1초당 1 C의 전하 이동.\n전자 1개 전하 $e = 1.602 \\times 10^{-19}\\ \\text{C}$",
    subject: "전기이론",
    topic: "직류회로",
    source: "preset",
    hint: "전하 = 전류 × 시간",
    example: {
      question: "2 A의 전류가 5분 동안 흐를 때 이동한 전하량은?",
      solution: [
        "$Q = I \\cdot t$",
        "$t = 5\\ \\text{분} = 300\\ \\text{초}$",
        "$Q = 2 \\times 300 = 600\\ \\text{C}$",
      ],
      answer: "$Q = 600\\ \\text{C}$",
    },
  },
  {
    id: "t-electric-energy",
    front: "전력량(전기 에너지)과 단위?",
    back: "$W = P \\cdot t$\n[J] = [W·s], 실용 단위 [kWh]\n$1\\ \\text{kWh} = 1000\\ \\text{W} \\times 3600\\ \\text{s} = 3.6 \\times 10^6\\ \\text{J}$",
    subject: "전기이론",
    topic: "직류회로",
    source: "preset",
    hint: "전력 × 시간, 요금 단위 kWh",
    example: {
      question: "1.5 kW 전열기를 4시간 사용했을 때 소비 전력량은?",
      solution: [
        "$W = P \\cdot t = 1.5\\ \\text{kW} \\times 4\\ \\text{h}$",
        "$W = 6\\ \\text{kWh}$",
      ],
      answer: "$W = 6\\ \\text{kWh}$",
    },
  },
  {
    id: "t-wheatstone-bridge",
    front: "휘트스톤 브리지 평형 조건?",
    back: "마주보는 변끼리의 곱이 같을 때 검류계 전류 0(평형).\n$R_1 \\cdot R_4 = R_2 \\cdot R_3$\n미지 저항의 정밀 측정에 사용.",
    subject: "전기이론",
    topic: "직류회로",
    source: "preset",
    hint: "대각 곱이 같으면 평형",
    example: {
      question: "브리지에서 $R_1 = 100\\ \\Omega$, $R_2 = 200\\ \\Omega$, $R_3 = 300\\ \\Omega$일 때 평형이 되는 $R_4$는?",
      solution: [
        "평형: $R_1 R_4 = R_2 R_3$",
        "$R_4 = \\dfrac{R_2 R_3}{R_1} = \\dfrac{200 \\times 300}{100}$",
        "$R_4 = 600\\ \\Omega$",
      ],
      answer: "$R_4 = 600\\ \\Omega$",
    },
  },
  {
    id: "t-rl-time-constant",
    front: "RL 회로 시정수 τ는?",
    back: "$\\tau = \\dfrac{L}{R}$ [초]\n전류 상승 $i(t) = \\dfrac{V}{R}\\left(1 - e^{-t/\\tau}\\right)$\n$t = 5\\tau$에서 약 99 % 도달. (RC는 $\\tau = RC$로 형태가 다름)",
    subject: "전기이론",
    topic: "직류회로",
    source: "preset",
    hint: "RL은 L/R, RC는 RC",
    example: {
      question: "$L = 0.5\\ \\text{H}$, $R = 100\\ \\Omega$인 RL 회로의 시정수는?",
      solution: [
        "$\\tau = \\dfrac{L}{R}$",
        "$\\tau = \\dfrac{0.5}{100} = 0.005\\ \\text{초} = 5\\ \\text{ms}$",
      ],
      answer: "$\\tau = 5\\ \\text{ms}$",
    },
  },

  // ===== 정전기 (11) =====
  {
    id: "t-capacitance-def",
    front: "정전용량의 정의?",
    back: "$C = \\dfrac{Q}{V}$ [F, 패럿]\n같은 전압에서 더 많은 전하를 저장할수록 용량이 크다.\n실용 단위: $\\mu\\text{F},\\ \\text{nF},\\ \\text{pF}$",
    subject: "전기이론",
    topic: "정전기",
    source: "preset",
    hint: "용량 = 전하 / 전압",
    example: {
      question: "100 V를 가했을 때 $2 \\times 10^{-4}\\ \\text{C}$이 충전되는 콘덴서의 용량은?",
      solution: [
        "$C = \\dfrac{Q}{V}$",
        "$C = \\dfrac{2 \\times 10^{-4}}{100} = 2 \\times 10^{-6}\\ \\text{F}$",
        "$C = 2\\ \\mu\\text{F}$",
      ],
      answer: "$C = 2\\ \\mu\\text{F}$",
    },
  },
  {
    id: "t-parallel-plate-cap",
    front: "평행판 콘덴서의 정전용량?",
    back: "$C = \\varepsilon \\cdot \\dfrac{A}{d} = \\varepsilon_0 \\varepsilon_s \\cdot \\dfrac{A}{d}$\n$\\varepsilon_0 = 8.855 \\times 10^{-12}\\ \\text{F/m}$\n극판 면적에 비례, 간격에 반비례.",
    subject: "전기이론",
    topic: "정전기",
    source: "preset",
    hint: "면적↑·간격↓ → 용량↑",
    example: {
      question: "극판을 2배 넓히고 간격을 절반으로 줄이면 정전용량은 몇 배?",
      solution: [
        "$C \\propto \\dfrac{A}{d}$",
        "면적 2배, 간격 $\\dfrac{1}{2}$",
        "$C' = \\dfrac{2A}{d/2} = 4 \\times \\dfrac{A}{d}$",
      ],
      answer: "4배",
    },
  },
  {
    id: "t-electric-field-e",
    front: "전계의 세기 E와 전위차?",
    back: "$E = \\dfrac{V}{d}$ [V/m] (평등 전계)\n점전하 전계: $E = \\dfrac{Q}{4\\pi\\varepsilon r^2} = 9 \\times 10^9 \\dfrac{Q}{\\varepsilon_s r^2}$\n힘 $F = QE$",
    subject: "전기이론",
    topic: "정전기",
    source: "preset",
    hint: "평등 전계는 V/d",
    example: {
      question: "간격 5 mm 평행판에 100 V를 가했을 때 내부 전계의 세기는?",
      solution: [
        "$E = \\dfrac{V}{d}$",
        "$E = \\dfrac{100}{5 \\times 10^{-3}}$",
        "$E = 2 \\times 10^{4}\\ \\text{V/m}$",
      ],
      answer: "$E = 2 \\times 10^{4}\\ \\text{V/m}$",
    },
  },
  {
    id: "t-electric-flux-density",
    front: "전속밀도 D와 가우스 법칙?",
    back: "$D = \\varepsilon E = \\dfrac{Q}{A}$ [$\\text{C/m}^2$]\n가우스 법칙: 폐곡면을 지나는 전속 = 내부 총 전하 $Q$.\n전속은 매질($\\varepsilon$)과 무관, 전계는 매질에 따라 달라짐.",
    subject: "전기이론",
    topic: "정전기",
    source: "preset",
    hint: "전속은 매질 무관",
    example: {
      question: "면적 $0.5\\ \\text{m}^2$ 극판에 $1 \\times 10^{-6}\\ \\text{C}$이 분포할 때 전속밀도는?",
      solution: [
        "$D = \\dfrac{Q}{A}$",
        "$D = \\dfrac{1 \\times 10^{-6}}{0.5}$",
        "$D = 2 \\times 10^{-6}\\ \\text{C/m}^2$",
      ],
      answer: "$D = 2 \\times 10^{-6}\\ \\text{C/m}^2$",
    },
  },
  {
    id: "t-dielectric-constant",
    front: "비유전율(유전체)의 효과?",
    back: "콘덴서 극판 사이에 비유전율 $\\varepsilon_s$ 유전체를 채우면 용량이 $\\varepsilon_s$배 증가.\n$C = \\varepsilon_s \\cdot C_0$\n공기·진공 $\\varepsilon_s \\approx 1$, 종이 약 2~3, 운모 약 5~7.",
    subject: "전기이론",
    topic: "정전기",
    source: "preset",
    hint: "유전체 채우면 용량 ε_s배",
    example: {
      question: "공기 콘덴서 용량 $4\\ \\mu\\text{F}$에 비유전율 5인 유전체를 채우면 용량은?",
      solution: [
        "$C = \\varepsilon_s \\cdot C_0$",
        "$C = 5 \\times 4 = 20\\ \\mu\\text{F}$",
      ],
      answer: "$C = 20\\ \\mu\\text{F}$",
    },
  },
  {
    id: "t-cap-charge-distribution",
    front: "직렬 콘덴서의 전하·전압 분배?",
    back: "직렬 콘덴서는 전하 Q가 모두 동일.\n전압은 용량에 반비례 분배: $V_n = \\dfrac{Q}{C_n}$\n→ 작은 용량 콘덴서에 더 큰 전압이 걸린다.",
    subject: "전기이론",
    topic: "정전기",
    source: "preset",
    hint: "직렬: 전하 같고 작은 C에 큰 V",
    example: {
      question: "$C_1 = 2\\ \\mu\\text{F}$, $C_2 = 4\\ \\mu\\text{F}$ 직렬에 60 V 인가 시 $C_1$ 양단 전압은?",
      solution: [
        "합성: $\\dfrac{1}{C} = \\dfrac{1}{2} + \\dfrac{1}{4} = \\dfrac{3}{4}$ → $C = \\dfrac{4}{3}\\ \\mu\\text{F}$",
        "$Q = C V = \\dfrac{4}{3} \\times 60 = 80\\ \\mu\\text{C}$",
        "$V_1 = \\dfrac{Q}{C_1} = \\dfrac{80}{2} = 40\\ \\text{V}$",
      ],
      answer: "$V_1 = 40\\ \\text{V}$",
    },
  },
  {
    id: "t-electric-potential",
    front: "점전하에 의한 전위 V?",
    back: "$V = \\dfrac{Q}{4\\pi\\varepsilon r} = 9 \\times 10^9 \\cdot \\dfrac{Q}{\\varepsilon_s r}$ [V]\n전위는 거리에 반비례 ($1/r$), 전계는 거리 제곱에 반비례 ($1/r^2$).",
    subject: "전기이론",
    topic: "정전기",
    source: "preset",
    hint: "전위 1/r, 전계 1/r²",
    example: {
      question: "$2\\ \\mu\\text{C}$ 점전하로부터 0.3 m 떨어진 점의 전위는? (공기)",
      solution: [
        "$V = 9 \\times 10^9 \\cdot \\dfrac{Q}{r}$",
        "$V = 9 \\times 10^9 \\times \\dfrac{2 \\times 10^{-6}}{0.3}$",
        "$V = 6 \\times 10^{4}\\ \\text{V} = 60\\ \\text{kV}$",
      ],
      answer: "$V = 60\\ \\text{kV}$",
    },
  },
  {
    id: "t-coulomb-medium",
    front: "유전체 속 쿨롱 힘의 변화?",
    back: "$F = \\dfrac{1}{4\\pi\\varepsilon_0\\varepsilon_s} \\cdot \\dfrac{Q_1 Q_2}{r^2}$\n비유전율 $\\varepsilon_s$인 매질 속에서는 진공일 때보다 힘이 $\\dfrac{1}{\\varepsilon_s}$로 감소.",
    subject: "전기이론",
    topic: "정전기",
    source: "preset",
    hint: "매질 속에서 힘은 1/ε_s",
    example: {
      question: "진공에서 작용하는 힘이 10 N일 때, 비유전율 5인 기름 속에 넣으면 힘은?",
      solution: [
        "$F_{매질} = \\dfrac{F_{진공}}{\\varepsilon_s}$",
        "$F = \\dfrac{10}{5} = 2\\ \\text{N}$",
      ],
      answer: "$F = 2\\ \\text{N}$",
    },
  },
  {
    id: "t-electrostatic-induction",
    front: "정전 유도 현상이란?",
    back: "대전체를 도체에 가까이 하면, 가까운 면에 반대 부호, 먼 면에 같은 부호 전하가 유도됨.\n전하의 이동(자유전자) 때문이며 절연체에서는 유전 분극으로 나타남.",
    subject: "전기이론",
    topic: "정전기",
    source: "preset",
    hint: "가까운 면=반대 부호",
    example: {
      question: "(+)대전체를 중성 금속구에 접근시키면 가까운 쪽에 유도되는 전하는?",
      solution: [
        "정전 유도: 가까운 면에 반대 부호",
        "(+)대전체 → 가까운 면 (−)전하 유도",
      ],
      answer: "음(−)전하",
    },
  },
  {
    id: "t-capacitor-withstand",
    front: "콘덴서의 내압과 직렬 연결?",
    back: "콘덴서마다 견딜 수 있는 최대 전압(내압)이 있다.\n직렬 시 작은 용량에 더 큰 전압이 걸리므로, 용량이 작은 콘덴서가 먼저 절연 파괴될 수 있다.\n→ 분담 전압이 내압을 넘지 않도록 설계.",
    subject: "전기이론",
    topic: "정전기",
    source: "preset",
    hint: "작은 C에 큰 전압 → 먼저 파괴",
    example: {
      question: "$1\\ \\mu\\text{F}$(내압 200 V)와 $2\\ \\mu\\text{F}$(내압 200 V) 직렬 회로에 가할 수 있는 최대 전압은?",
      solution: [
        "직렬에서 전하 동일, 전압은 용량 반비례",
        "$1\\ \\mu\\text{F}$가 내압 200 V 도달 시 $Q = 1\\ \\mu\\text{F} \\times 200 = 200\\ \\mu\\text{C}$",
        "$V_2 = \\dfrac{200}{2} = 100\\ \\text{V}$",
        "총 전압 $= 200 + 100 = 300\\ \\text{V}$",
      ],
      answer: "최대 300 V (작은 콘덴서가 한계)",
    },
  },
  {
    id: "t-capacitor-parallel-energy",
    front: "콘덴서 병렬 합성과 합성 에너지?",
    back: "병렬: $C = C_1 + C_2 + \\cdots$, 전압 V 공통.\n총 저장 에너지 $W = \\dfrac{1}{2}(C_1 + C_2)V^2$\n같은 전압이므로 각 콘덴서 에너지의 단순 합.",
    subject: "전기이론",
    topic: "정전기",
    source: "preset",
    hint: "병렬은 전압 공통, 용량 덧셈",
    example: {
      question: "$3\\ \\mu\\text{F}$, $5\\ \\mu\\text{F}$ 병렬에 100 V 인가 시 총 저장 에너지는?",
      solution: [
        "$C = 3 + 5 = 8\\ \\mu\\text{F}$",
        "$W = \\dfrac{1}{2} C V^2 = \\dfrac{1}{2} \\times 8 \\times 10^{-6} \\times 100^2$",
        "$W = \\dfrac{1}{2} \\times 8 \\times 10^{-6} \\times 10^4 = 0.04\\ \\text{J}$",
      ],
      answer: "$W = 0.04\\ \\text{J} = 40\\ \\text{mJ}$",
    },
  },

  // ===== 자기·자기회로 (11) =====
  {
    id: "t-biot-savart-straight",
    front: "직선 도체 주위 자계의 세기?",
    back: "$H = \\dfrac{I}{2\\pi r}$ [AT/m]\n무한 직선 도체에서 거리 $r$만큼 떨어진 점.\n암페어 오른나사 법칙으로 방향 결정.",
    subject: "전기이론",
    topic: "자기·자기회로",
    source: "preset",
    hint: "직선: I / (2πr)",
    example: {
      question: "10 A가 흐르는 직선 도체에서 5 cm 떨어진 점의 자계 세기는?",
      solution: [
        "$H = \\dfrac{I}{2\\pi r}$",
        "$H = \\dfrac{10}{2\\pi \\times 0.05}$",
        "$H = \\dfrac{10}{0.314} \\approx 31.8\\ \\text{AT/m}$",
      ],
      answer: "$H \\approx 31.8\\ \\text{AT/m}$",
    },
  },
  {
    id: "t-circular-coil-h",
    front: "원형 코일 중심의 자계?",
    back: "$H = \\dfrac{N I}{2 r}$ [AT/m]\n$N$ 권수, $r$ 코일 반지름.\n코일 중심에서의 자계 세기.",
    subject: "전기이론",
    topic: "자기·자기회로",
    source: "preset",
    hint: "원형 중심: NI / 2r",
    example: {
      question: "반지름 10 cm, 50회 감은 원형 코일에 2 A가 흐를 때 중심 자계는?",
      solution: [
        "$H = \\dfrac{N I}{2 r}$",
        "$H = \\dfrac{50 \\times 2}{2 \\times 0.1}$",
        "$H = \\dfrac{100}{0.2} = 500\\ \\text{AT/m}$",
      ],
      answer: "$H = 500\\ \\text{AT/m}$",
    },
  },
  {
    id: "t-flux-density-b",
    front: "자속밀도 B와 자속 Φ의 관계?",
    back: "$B = \\dfrac{\\Phi}{A}$ [Wb/$\\text{m}^2$ = T]\n$B = \\mu H = \\mu_0 \\mu_s H$\n$\\mu_0 = 4\\pi \\times 10^{-7}\\ \\text{H/m}$",
    subject: "전기이론",
    topic: "자기·자기회로",
    source: "preset",
    hint: "자속밀도 = 자속 / 면적",
    example: {
      question: "단면적 $5 \\times 10^{-4}\\ \\text{m}^2$를 통과하는 자속이 $2 \\times 10^{-3}\\ \\text{Wb}$일 때 자속밀도는?",
      solution: [
        "$B = \\dfrac{\\Phi}{A}$",
        "$B = \\dfrac{2 \\times 10^{-3}}{5 \\times 10^{-4}}$",
        "$B = 4\\ \\text{T}$",
      ],
      answer: "$B = 4\\ \\text{T}$",
    },
  },
  {
    id: "t-magnetic-reluctance",
    front: "자기 저항(릴럭턴스)과 옴의 법칙?",
    back: "자기 옴의 법칙: $\\Phi = \\dfrac{F}{R_m}$\n기자력 $F = N I$ [AT]\n자기저항 $R_m = \\dfrac{l}{\\mu A}$ [AT/Wb]\n전기회로의 $V = IR$과 대응 구조.",
    subject: "전기이론",
    topic: "자기·자기회로",
    source: "preset",
    hint: "Φ↔I, F↔V, R_m↔R",
    example: {
      question: "권수 200회에 0.5 A가 흐르고 자기저항이 $5 \\times 10^4\\ \\text{AT/Wb}$일 때 자속은?",
      solution: [
        "기자력 $F = N I = 200 \\times 0.5 = 100\\ \\text{AT}$",
        "$\\Phi = \\dfrac{F}{R_m} = \\dfrac{100}{5 \\times 10^4}$",
        "$\\Phi = 2 \\times 10^{-3}\\ \\text{Wb}$",
      ],
      answer: "$\\Phi = 2\\ \\text{mWb}$",
    },
  },
  {
    id: "t-mmf",
    front: "기자력(MMF)이란?",
    back: "자속을 만드는 원천. $F = N I$ [AT, 암페어턴]\n전기회로의 기전력에 대응.\n자기회로에서 $F = \\Phi \\cdot R_m = H \\cdot l$.",
    subject: "전기이론",
    topic: "자기·자기회로",
    source: "preset",
    hint: "기자력 = 권수 × 전류",
    example: {
      question: "500회 코일에 0.4 A가 흐를 때의 기자력은?",
      solution: [
        "$F = N I$",
        "$F = 500 \\times 0.4 = 200\\ \\text{AT}$",
      ],
      answer: "$F = 200\\ \\text{AT}$",
    },
  },
  {
    id: "t-force-on-conductor",
    front: "자기장 속 도체가 받는 힘?",
    back: "$F = B I l \\sin\\theta$ [N]\n자속밀도 $B$, 전류 $I$, 도체 길이 $l$, 자기장과 전류 각 $\\theta$.\n방향: 플레밍 왼손 법칙 (전동기 원리).",
    subject: "전기이론",
    topic: "자기·자기회로",
    source: "preset",
    hint: "F = BIl·sinθ, 왼손 법칙",
    example: {
      question: "$B = 0.5\\ \\text{T}$, 길이 0.2 m 도체에 10 A가 수직($\\theta=90°$)으로 흐를 때 힘은?",
      solution: [
        "$F = B I l \\sin\\theta$",
        "$F = 0.5 \\times 10 \\times 0.2 \\times 1$",
        "$F = 1\\ \\text{N}$",
      ],
      answer: "$F = 1\\ \\text{N}$",
    },
  },
  {
    id: "t-flemings-left-hand",
    front: "플레밍 왼손 법칙?",
    back: "전동기에 적용. 왼손 세 손가락을 직각으로:\n엄지 = 힘(운동) F\n검지 = 자속밀도 B\n중지 = 전류 I\n(오른손 법칙은 발전기 — 유도 기전력 방향)",
    subject: "전기이론",
    topic: "자기·자기회로",
    source: "preset",
    hint: "왼손=전동기, 엄지=힘",
    example: {
      question: "자기장이 위→아래, 전류가 앞→뒤로 흐르는 도체가 받는 힘의 방향을 정하는 법칙은?",
      solution: [
        "전류가 흐르는 도체가 받는 힘 → 전동기 원리",
        "→ 플레밍 왼손 법칙 적용",
      ],
      answer: "플레밍 왼손 법칙 (엄지=힘)",
    },
  },
  {
    id: "t-magnetic-energy-density",
    front: "자기장의 단위 체적당 에너지?",
    back: "$w = \\dfrac{1}{2} B H = \\dfrac{B^2}{2\\mu} = \\dfrac{1}{2}\\mu H^2$ [J/$\\text{m}^3$]\n자기장이 공간에 저장하는 에너지 밀도.",
    subject: "전기이론",
    topic: "자기·자기회로",
    source: "preset",
    hint: "w = ½BH = B²/2μ",
    example: {
      question: "공기 중 $B = 1\\ \\text{T}$일 때 단위 체적당 자기 에너지는? ($\\mu_0 = 4\\pi \\times 10^{-7}$)",
      solution: [
        "$w = \\dfrac{B^2}{2\\mu_0}$",
        "$w = \\dfrac{1^2}{2 \\times 4\\pi \\times 10^{-7}}$",
        "$w = \\dfrac{1}{2.513 \\times 10^{-6}} \\approx 3.98 \\times 10^{5}\\ \\text{J/m}^3$",
      ],
      answer: "약 $4 \\times 10^{5}\\ \\text{J/m}^3$",
    },
  },
  {
    id: "t-hysteresis-loss",
    front: "히스테리시스 손실과 자성체?",
    back: "자성체를 반복 자화할 때 히스테리시스 곡선 면적만큼 손실 발생.\n슈타인메츠: $P_h = \\eta f B_{max}^{1.6}$ [W]\n변압기 철심은 손실 작은 규소강판 사용.",
    subject: "전기이론",
    topic: "자기·자기회로",
    source: "preset",
    hint: "곡선 면적 = 1주기 손실",
    example: {
      question: "주파수만 60 Hz에서 120 Hz로 2배 올리고 다른 조건이 같으면 히스테리시스 손실은?",
      solution: [
        "$P_h \\propto f$ (다른 조건 일정)",
        "주파수 2배 → 손실도 2배",
      ],
      answer: "2배 (주파수에 비례)",
    },
  },
  {
    id: "t-magnetic-circuit-airgap",
    front: "공극(에어갭)이 자기회로에 미치는 영향?",
    back: "공극은 투자율이 작아($\\mu_0$) 자기저항이 매우 크다.\n전체 자기저항 $R_m = R_{철심} + R_{공극}$ (직렬 합).\n작은 공극도 큰 기자력을 요구 → 자속 감소.",
    subject: "전기이론",
    topic: "자기·자기회로",
    source: "preset",
    hint: "공극은 자기저항이 큼",
    example: {
      question: "철심 자기저항 $1000\\ \\text{AT/Wb}$, 공극 자기저항 $9000\\ \\text{AT/Wb}$일 때 합성 자기저항은?",
      solution: [
        "직렬: $R_m = R_{철} + R_{공}$",
        "$R_m = 1000 + 9000 = 10000\\ \\text{AT/Wb}$",
      ],
      answer: "$R_m = 10000\\ \\text{AT/Wb}$",
    },
  },
  {
    id: "t-permeability",
    front: "투자율과 비투자율?",
    back: "$\\mu = \\mu_0 \\mu_s$ [H/m]\n$\\mu_0 = 4\\pi \\times 10^{-7}\\ \\text{H/m}$ (진공)\n비투자율 $\\mu_s$: 공기 ≈ 1, 강자성체(철) 수백~수천.\n클수록 자속이 잘 통과.",
    subject: "전기이론",
    topic: "자기·자기회로",
    source: "preset",
    hint: "μ = μ₀ × μ_s",
    example: {
      question: "비투자율 2000인 철심의 투자율은?",
      solution: [
        "$\\mu = \\mu_0 \\mu_s$",
        "$\\mu = 4\\pi \\times 10^{-7} \\times 2000$",
        "$\\mu \\approx 2.51 \\times 10^{-3}\\ \\text{H/m}$",
      ],
      answer: "$\\mu \\approx 2.51 \\times 10^{-3}\\ \\text{H/m}$",
    },
  },

  // ===== 전자기 유도 (11) =====
  {
    id: "t-faraday-law",
    front: "패러데이 전자유도 법칙?",
    back: "$e = -N \\dfrac{d\\Phi}{dt}$ [V]\n코일 쇄교 자속의 시간 변화율에 비례한 기전력 유도.\n(−) 부호 = 렌츠의 법칙(변화 방해 방향).",
    subject: "전기이론",
    topic: "전자기 유도",
    source: "preset",
    hint: "e = -N dΦ/dt",
    example: {
      question: "200회 코일의 자속이 0.1초 동안 $0.02\\ \\text{Wb}$ 변할 때 유도 기전력 크기는?",
      solution: [
        "$|e| = N \\dfrac{\\Delta\\Phi}{\\Delta t}$",
        "$|e| = 200 \\times \\dfrac{0.02}{0.1}$",
        "$|e| = 200 \\times 0.2 = 40\\ \\text{V}$",
      ],
      answer: "$|e| = 40\\ \\text{V}$",
    },
  },
  {
    id: "t-lenz-law",
    front: "렌츠의 법칙?",
    back: "유도 전류는 자속의 변화를 방해하는 방향으로 흐른다.\n에너지 보존 법칙의 결과 (변화를 거스르려면 일이 필요).\n패러데이 식의 (−) 부호로 표현.",
    subject: "전기이론",
    topic: "전자기 유도",
    source: "preset",
    hint: "변화를 방해하는 방향",
    example: {
      question: "코일에 N극을 가까이 할 때 코일 측에 유도되는 자극은?",
      solution: [
        "렌츠 법칙: 접근(변화)을 방해",
        "다가오는 N극을 밀어내야 함",
        "→ 코일 마주보는 면이 N극이 됨(반발)",
      ],
      answer: "N극 (밀어내는 방향)",
    },
  },
  {
    id: "t-motional-emf",
    front: "운동 도체의 유도 기전력?",
    back: "$e = B l v \\sin\\theta$ [V]\n자속밀도 $B$ 속을 도체가 속도 $v$로 운동.\n방향: 플레밍 오른손 법칙 (발전기 원리).",
    subject: "전기이론",
    topic: "전자기 유도",
    source: "preset",
    hint: "e = Blv, 오른손 법칙",
    example: {
      question: "$B = 0.8\\ \\text{T}$ 자장 속에서 길이 0.5 m 도체가 4 m/s로 수직 운동할 때 유도 기전력은?",
      solution: [
        "$e = B l v \\sin\\theta$",
        "$e = 0.8 \\times 0.5 \\times 4 \\times 1$",
        "$e = 1.6\\ \\text{V}$",
      ],
      answer: "$e = 1.6\\ \\text{V}$",
    },
  },
  {
    id: "t-flemings-right-hand",
    front: "플레밍 오른손 법칙?",
    back: "발전기에 적용. 오른손 세 손가락 직각:\n엄지 = 운동(속도) v\n검지 = 자속밀도 B\n중지 = 유도 기전력·전류 e\n(왼손은 전동기)",
    subject: "전기이론",
    topic: "전자기 유도",
    source: "preset",
    hint: "오른손=발전기, 중지=기전력",
    example: {
      question: "도체를 자기장 속에서 움직일 때 발생하는 기전력의 방향을 정하는 법칙은?",
      solution: [
        "운동 → 기전력 발생 (발전기 원리)",
        "→ 플레밍 오른손 법칙",
      ],
      answer: "플레밍 오른손 법칙",
    },
  },
  {
    id: "t-solenoid-inductance",
    front: "솔레노이드(환상) 자기 인덕턴스?",
    back: "$L = \\dfrac{N\\Phi}{I} = \\dfrac{\\mu A N^2}{l}$ [H]\n권수의 제곱에 비례 ($L \\propto N^2$).\n→ 권수 2배면 인덕턴스 4배.",
    subject: "전기이론",
    topic: "전자기 유도",
    source: "preset",
    hint: "L ∝ N² (제곱 비례)",
    example: {
      question: "어떤 코일의 권수를 3배로 늘리면 자기 인덕턴스는 몇 배?",
      solution: [
        "$L \\propto N^2$",
        "$L' = 3^2 \\times L = 9 L$",
      ],
      answer: "9배",
    },
  },
  {
    id: "t-coupling-coefficient",
    front: "결합계수 k와 상호 인덕턴스?",
    back: "$M = k\\sqrt{L_1 L_2}$\n$k$ 결합계수 ($0 \\le k \\le 1$).\n$k=1$ 완전 결합(누설 자속 0), $k=0$ 결합 없음.",
    subject: "전기이론",
    topic: "전자기 유도",
    source: "preset",
    hint: "M = k√(L₁L₂)",
    example: {
      question: "$L_1 = 4\\ \\text{H}$, $L_2 = 9\\ \\text{H}$, 결합계수 $k = 0.5$일 때 상호 인덕턴스는?",
      solution: [
        "$M = k\\sqrt{L_1 L_2}$",
        "$M = 0.5 \\times \\sqrt{4 \\times 9}$",
        "$M = 0.5 \\times 6 = 3\\ \\text{H}$",
      ],
      answer: "$M = 3\\ \\text{H}$",
    },
  },
  {
    id: "t-inductor-series",
    front: "인덕턴스의 직렬 합성 (상호 결합)?",
    back: "가동 접속(자속 도움): $L = L_1 + L_2 + 2M$\n차동 접속(자속 상쇄): $L = L_1 + L_2 - 2M$\n결합 없으면 단순히 $L = L_1 + L_2$.",
    subject: "전기이론",
    topic: "전자기 유도",
    source: "preset",
    hint: "가동 +2M, 차동 -2M",
    example: {
      question: "$L_1 = 5\\ \\text{H}$, $L_2 = 3\\ \\text{H}$, $M = 2\\ \\text{H}$를 가동 접속하면 합성 인덕턴스는?",
      solution: [
        "가동 접속: $L = L_1 + L_2 + 2M$",
        "$L = 5 + 3 + 2 \\times 2$",
        "$L = 12\\ \\text{H}$",
      ],
      answer: "$L = 12\\ \\text{H}$",
    },
  },
  {
    id: "t-eddy-current",
    front: "와전류와 와전류 손실?",
    back: "변화하는 자속이 도체 내부에 맴돌이 전류 유도 → 열손실.\n$P_e \\propto f^2 B_{max}^2 t^2$ (t: 철판 두께)\n→ 철심을 얇게 적층(성층)·절연하여 손실 감소.",
    subject: "전기이론",
    topic: "전자기 유도",
    source: "preset",
    hint: "철심 성층으로 저감",
    example: {
      question: "와전류 손실을 줄이기 위해 변압기 철심에 적용하는 구조는?",
      solution: [
        "와전류 경로를 끊어야 함",
        "얇은 규소강판을 절연하여 적층(성층 철심)",
      ],
      answer: "성층(적층) 철심 + 규소강판",
    },
  },
  {
    id: "t-inductor-energy-detail",
    front: "인덕터 에너지와 전류 차단 시 현상?",
    back: "$W = \\dfrac{1}{2} L I^2$ [J]\n인덕터 전류를 갑자기 끊으면 $\\dfrac{di}{dt}$가 매우 커져 큰 역기전력(서지) 발생.\n→ 스위치 아크, 접점 손상 원인.",
    subject: "전기이론",
    topic: "전자기 유도",
    source: "preset",
    hint: "전류 급차단 → 큰 서지 전압",
    example: {
      question: "$L = 0.4\\ \\text{H}$ 코일에 5 A가 흐를 때 저장 에너지는?",
      solution: [
        "$W = \\dfrac{1}{2} L I^2$",
        "$W = \\dfrac{1}{2} \\times 0.4 \\times 5^2$",
        "$W = 0.2 \\times 25 = 5\\ \\text{J}$",
      ],
      answer: "$W = 5\\ \\text{J}$",
    },
  },
  {
    id: "t-transformer-emf-equation",
    front: "변압기 유기 기전력 공식?",
    back: "$E = 4.44\\, f\\, N\\, \\Phi_{max}$ [V]\n$f$ 주파수, $N$ 권수, $\\Phi_{max}$ 최대 자속.\n계수 4.44 = $2\\pi/\\sqrt{2}$ (정현파 실효값 기준).",
    subject: "전기이론",
    topic: "전자기 유도",
    source: "preset",
    hint: "E = 4.44 f N Φ_max",
    example: {
      question: "60 Hz, 권수 100회, 최대자속 $0.01\\ \\text{Wb}$일 때 유기 기전력은?",
      solution: [
        "$E = 4.44\\, f\\, N\\, \\Phi_{max}$",
        "$E = 4.44 \\times 60 \\times 100 \\times 0.01$",
        "$E = 266.4\\ \\text{V}$",
      ],
      answer: "$E \\approx 266\\ \\text{V}$",
    },
  },
  {
    id: "t-self-induced-emf",
    front: "자기 유도 기전력 (전류 변화)?",
    back: "$e = -L \\dfrac{di}{dt}$ [V]\n코일 자신의 전류 변화가 만드는 역기전력.\n전류 변화를 방해 → 인덕터는 직류엔 단락, 교류엔 임피던스로 작용.",
    subject: "전기이론",
    topic: "전자기 유도",
    source: "preset",
    hint: "e = -L di/dt",
    example: {
      question: "$L = 0.2\\ \\text{H}$ 코일의 전류가 0.05초에 4 A 변할 때 자기 유도 기전력 크기는?",
      solution: [
        "$|e| = L \\dfrac{\\Delta i}{\\Delta t}$",
        "$|e| = 0.2 \\times \\dfrac{4}{0.05}$",
        "$|e| = 0.2 \\times 80 = 16\\ \\text{V}$",
      ],
      answer: "$|e| = 16\\ \\text{V}$",
    },
  },

  // ===== 교류회로 (11) =====
  {
    id: "t-ac-frequency-period",
    front: "교류의 주파수·주기·각속도?",
    back: "주기 $T = \\dfrac{1}{f}$ [s]\n각속도 $\\omega = 2\\pi f$ [rad/s]\n순시값 $v = V_m \\sin(\\omega t + \\theta)$\n한국 상용 주파수: 60 Hz.",
    subject: "전기이론",
    topic: "교류회로",
    source: "preset",
    hint: "ω = 2πf, T = 1/f",
    example: {
      question: "60 Hz 교류의 주기와 각속도는?",
      solution: [
        "$T = \\dfrac{1}{f} = \\dfrac{1}{60} \\approx 0.0167\\ \\text{s}$",
        "$\\omega = 2\\pi f = 2\\pi \\times 60 \\approx 377\\ \\text{rad/s}$",
      ],
      answer: "$T \\approx 16.7\\ \\text{ms},\\ \\omega \\approx 377\\ \\text{rad/s}$",
    },
  },
  {
    id: "t-inductive-reactance",
    front: "유도 리액턴스 $X_L$?",
    back: "$X_L = \\omega L = 2\\pi f L$ [$\\Omega$]\n주파수에 비례 → 고주파일수록 코일이 전류를 더 방해.\n전압이 전류보다 90° 앞섬(전류 지상).",
    subject: "전기이론",
    topic: "교류회로",
    source: "preset",
    hint: "X_L = 2πfL, 주파수 비례",
    example: {
      question: "60 Hz에서 $L = 0.1\\ \\text{H}$ 코일의 유도 리액턴스는?",
      solution: [
        "$X_L = 2\\pi f L$",
        "$X_L = 2\\pi \\times 60 \\times 0.1$",
        "$X_L \\approx 37.7\\ \\Omega$",
      ],
      answer: "$X_L \\approx 37.7\\ \\Omega$",
    },
  },
  {
    id: "t-capacitive-reactance",
    front: "용량 리액턴스 $X_C$?",
    back: "$X_C = \\dfrac{1}{\\omega C} = \\dfrac{1}{2\\pi f C}$ [$\\Omega$]\n주파수에 반비례 → 고주파일수록 콘덴서가 잘 통함.\n전류가 전압보다 90° 앞섬(전류 진상).",
    subject: "전기이론",
    topic: "교류회로",
    source: "preset",
    hint: "X_C = 1/(2πfC), 주파수 반비례",
    example: {
      question: "60 Hz에서 $C = 100\\ \\mu\\text{F}$ 콘덴서의 용량 리액턴스는?",
      solution: [
        "$X_C = \\dfrac{1}{2\\pi f C}$",
        "$X_C = \\dfrac{1}{2\\pi \\times 60 \\times 100 \\times 10^{-6}}$",
        "$X_C = \\dfrac{1}{0.0377} \\approx 26.5\\ \\Omega$",
      ],
      answer: "$X_C \\approx 26.5\\ \\Omega$",
    },
  },
  {
    id: "t-rl-series-impedance",
    front: "RL 직렬 회로의 임피던스와 위상?",
    back: "$Z = \\sqrt{R^2 + X_L^2}$\n위상각 $\\theta = \\tan^{-1}\\dfrac{X_L}{R}$ (전류가 전압보다 지상)\n역률 $\\cos\\theta = \\dfrac{R}{Z}$.",
    subject: "전기이론",
    topic: "교류회로",
    source: "preset",
    hint: "Z=√(R²+X_L²), 전류 지상",
    example: {
      question: "$R = 4\\ \\Omega$, $X_L = 3\\ \\Omega$인 RL 직렬 회로의 임피던스와 역률은?",
      solution: [
        "$Z = \\sqrt{4^2 + 3^2} = \\sqrt{25} = 5\\ \\Omega$",
        "$\\cos\\theta = \\dfrac{R}{Z} = \\dfrac{4}{5} = 0.8$",
      ],
      answer: "$Z = 5\\ \\Omega,\\ \\cos\\theta = 0.8$",
    },
  },
  {
    id: "t-rc-series-impedance",
    front: "RC 직렬 회로의 임피던스와 위상?",
    back: "$Z = \\sqrt{R^2 + X_C^2}$\n위상각 $\\theta = \\tan^{-1}\\dfrac{X_C}{R}$ (전류가 전압보다 진상)\n역률 $\\cos\\theta = \\dfrac{R}{Z}$.",
    subject: "전기이론",
    topic: "교류회로",
    source: "preset",
    hint: "RC는 전류 진상",
    example: {
      question: "$R = 8\\ \\Omega$, $X_C = 6\\ \\Omega$인 RC 직렬 회로의 임피던스는?",
      solution: [
        "$Z = \\sqrt{R^2 + X_C^2}$",
        "$Z = \\sqrt{8^2 + 6^2} = \\sqrt{100}$",
        "$Z = 10\\ \\Omega$",
      ],
      answer: "$Z = 10\\ \\Omega$",
    },
  },
  {
    id: "t-rlc-parallel-resonance",
    front: "RLC 병렬 공진의 특징?",
    back: "공진 주파수 $f_0 = \\dfrac{1}{2\\pi\\sqrt{LC}}$ (직렬과 동일)\n병렬 공진에서는 임피던스가 최대, 전체 전류 최소.\n(직렬 공진은 임피던스 최소·전류 최대 — 정반대)",
    subject: "전기이론",
    topic: "교류회로",
    source: "preset",
    hint: "병렬 공진 = 임피던스 최대",
    example: {
      question: "$L = 1\\ \\text{mH}$, $C = 1\\ \\mu\\text{F}$인 병렬 공진 회로의 공진 주파수는?",
      solution: [
        "$f_0 = \\dfrac{1}{2\\pi\\sqrt{LC}}$",
        "$LC = 10^{-3} \\times 10^{-6} = 10^{-9}$",
        "$\\sqrt{LC} = 3.16 \\times 10^{-5}$",
        "$f_0 = \\dfrac{1}{2\\pi \\times 3.16 \\times 10^{-5}} \\approx 5033\\ \\text{Hz}$",
      ],
      answer: "약 5.03 kHz",
    },
  },
  {
    id: "t-power-factor-correction",
    front: "역률 개선(콘덴서 병렬)의 효과?",
    back: "유도성 부하에 콘덴서를 병렬로 달아 진상 무효전력을 공급 → 역률 상승.\n효과: 선로 전류·손실 감소, 전압강하 감소, 설비 용량 여유.\n필요 용량 $Q_C = P(\\tan\\theta_1 - \\tan\\theta_2)$.",
    subject: "전기이론",
    topic: "교류회로",
    source: "preset",
    hint: "병렬 콘덴서로 무효전력 보상",
    example: {
      question: "역률 개선용 콘덴서를 부하에 어떻게 연결하는가?",
      solution: [
        "유도성 부하의 지상 무효전력 보상",
        "콘덴서(진상)를 부하와 병렬 연결",
      ],
      answer: "부하와 병렬로 연결 (진상 보상)",
    },
  },
  {
    id: "t-rl-parallel",
    front: "R, L 병렬 회로의 합성 어드미턴스?",
    back: "$Y = \\sqrt{G^2 + B^2}$, $G = \\dfrac{1}{R}$, $B_L = \\dfrac{1}{X_L}$\n임피던스 $Z = \\dfrac{1}{Y}$.\n병렬 회로는 어드미턴스로 푸는 것이 편리.",
    subject: "전기이론",
    topic: "교류회로",
    source: "preset",
    hint: "병렬은 어드미턴스로",
    example: {
      question: "$R = 10\\ \\Omega$과 $X_L = 10\\ \\Omega$ 병렬 회로의 합성 임피던스 크기는?",
      solution: [
        "$G = \\dfrac{1}{10} = 0.1$, $B_L = \\dfrac{1}{10} = 0.1$",
        "$Y = \\sqrt{0.1^2 + 0.1^2} = \\sqrt{0.02} \\approx 0.1414\\ \\text{S}$",
        "$Z = \\dfrac{1}{Y} \\approx 7.07\\ \\Omega$",
      ],
      answer: "$Z \\approx 7.07\\ \\Omega$",
    },
  },
  {
    id: "t-instantaneous-power",
    front: "교류 순시 전력과 평균 전력?",
    back: "순시전력 $p(t) = v(t)\\cdot i(t)$ (맥동).\n평균(유효)전력 $P = V I \\cos\\theta$ [W]\n순수 L·C는 평균전력 0 (에너지 왕복만, 무효).",
    subject: "전기이론",
    topic: "교류회로",
    source: "preset",
    hint: "순수 리액턴스 평균전력 0",
    example: {
      question: "실효전압 100 V, 실효전류 5 A, 위상차 60°인 회로의 유효전력은?",
      solution: [
        "$P = V I \\cos\\theta$",
        "$P = 100 \\times 5 \\times \\cos 60°$",
        "$P = 500 \\times 0.5 = 250\\ \\text{W}$",
      ],
      answer: "$P = 250\\ \\text{W}$",
    },
  },
  {
    id: "t-form-crest-factor",
    front: "파형률과 파고율?",
    back: "파형률 $= \\dfrac{\\text{실효값}}{\\text{평균값}}$ (정현파 ≈ 1.11)\n파고율 $= \\dfrac{\\text{최댓값}}{\\text{실효값}}$ (정현파 ≈ 1.414)\n파형의 모양을 나타내는 지표.",
    subject: "전기이론",
    topic: "교류회로",
    source: "preset",
    hint: "정현파 파형률 1.11, 파고율 1.41",
    example: {
      question: "정현파의 파고율은? (실효값 = $V_m/\\sqrt{2}$)",
      solution: [
        "파고율 $= \\dfrac{V_m}{V_{rms}} = \\dfrac{V_m}{V_m/\\sqrt{2}}$",
        "$= \\sqrt{2} \\approx 1.414$",
      ],
      answer: "약 1.414",
    },
  },
  {
    id: "t-complex-impedance",
    front: "복소 임피던스 표현?",
    back: "$Z = R + jX$ [$\\Omega$]\n$X = X_L - X_C$ (유도성 +, 용량성 −).\n크기 $|Z| = \\sqrt{R^2 + X^2}$, 위상 $\\theta = \\tan^{-1}\\dfrac{X}{R}$.",
    subject: "전기이론",
    topic: "교류회로",
    source: "preset",
    hint: "Z = R + jX (직각 좌표)",
    example: {
      question: "$Z = 6 + j8\\ \\Omega$의 크기와 위상각은?",
      solution: [
        "$|Z| = \\sqrt{6^2 + 8^2} = \\sqrt{100} = 10\\ \\Omega$",
        "$\\theta = \\tan^{-1}\\dfrac{8}{6} \\approx 53.1°$",
      ],
      answer: "$|Z| = 10\\ \\Omega,\\ \\theta \\approx 53.1°$",
    },
  },

  // ===== 3상 교류 (11) =====
  {
    id: "t-3phase-y-relation",
    front: "3상 Y(성형) 결선의 전압·전류 관계?",
    back: "$V_L = \\sqrt{3}\\, V_p$, $I_L = I_p$\n선간전압이 상전압보다 $\\sqrt{3}$배 크고 30° 앞섬.\n중성점 인출 가능(4선식).",
    subject: "전기이론",
    topic: "3상 교류",
    source: "preset",
    hint: "Y: 선전압=√3 상전압",
    example: {
      question: "Y결선 상전압 220 V일 때 선간전압은?",
      solution: [
        "$V_L = \\sqrt{3}\\, V_p$",
        "$V_L = 1.732 \\times 220 \\approx 381\\ \\text{V}$",
      ],
      answer: "$V_L \\approx 381\\ \\text{V}$ (220/380 계통)",
    },
  },
  {
    id: "t-3phase-delta-relation",
    front: "3상 Δ(삼각) 결선의 전압·전류 관계?",
    back: "$V_L = V_p$, $I_L = \\sqrt{3}\\, I_p$\n선전류가 상전류보다 $\\sqrt{3}$배 크고 30° 지상.\nY결선과 정반대 구조.",
    subject: "전기이론",
    topic: "3상 교류",
    source: "preset",
    hint: "Δ: 선전류=√3 상전류",
    example: {
      question: "Δ결선 상전류가 20 A일 때 선전류는?",
      solution: [
        "$I_L = \\sqrt{3}\\, I_p$",
        "$I_L = 1.732 \\times 20 \\approx 34.6\\ \\text{A}$",
      ],
      answer: "$I_L \\approx 34.6\\ \\text{A}$",
    },
  },
  {
    id: "t-3phase-apparent-power",
    front: "3상 피상·무효 전력?",
    back: "피상전력 $S = \\sqrt{3}\\, V_L I_L$ [VA]\n유효전력 $P = \\sqrt{3}\\, V_L I_L \\cos\\theta$ [W]\n무효전력 $Q = \\sqrt{3}\\, V_L I_L \\sin\\theta$ [Var]",
    subject: "전기이론",
    topic: "3상 교류",
    source: "preset",
    hint: "S = √3 V_L I_L",
    example: {
      question: "선간전압 380 V, 선전류 10 A인 3상 부하의 피상전력은?",
      solution: [
        "$S = \\sqrt{3}\\, V_L I_L$",
        "$S = 1.732 \\times 380 \\times 10$",
        "$S \\approx 6581\\ \\text{VA} \\approx 6.58\\ \\text{kVA}$",
      ],
      answer: "약 6.58 kVA",
    },
  },
  {
    id: "t-3phase-balanced-current",
    front: "평형 3상의 중성선 전류?",
    back: "평형 3상에서는 세 상 전류의 합이 0.\n$I_a + I_b + I_c = 0$ → 중성선 전류 0.\n→ 평형이면 중성선이 없어도 됨(3선식 가능).",
    subject: "전기이론",
    topic: "3상 교류",
    source: "preset",
    hint: "평형이면 중성선 전류 0",
    example: {
      question: "완전 평형 3상 Y부하에서 각 상 전류가 10 A일 때 중성선에 흐르는 전류는?",
      solution: [
        "평형 3상: 위상 120° 간격으로 벡터 합 = 0",
        "$I_a + I_b + I_c = 0$",
      ],
      answer: "0 A (이론상)",
    },
  },
  {
    id: "t-2wattmeter",
    front: "2전력계법(3상 전력 측정)?",
    back: "3상 3선식 전력을 전력계 2개로 측정.\n$P = W_1 + W_2$ (총 유효전력)\n역률 $\\cos\\theta = \\dfrac{W_1 + W_2}{2\\sqrt{W_1^2 + W_2^2 - W_1 W_2}}$",
    subject: "전기이론",
    topic: "3상 교류",
    source: "preset",
    hint: "P = W₁ + W₂",
    example: {
      question: "2전력계법에서 $W_1 = 600\\ \\text{W}$, $W_2 = 400\\ \\text{W}$일 때 3상 총 전력은?",
      solution: [
        "$P = W_1 + W_2$",
        "$P = 600 + 400 = 1000\\ \\text{W}$",
      ],
      answer: "$P = 1000\\ \\text{W}$",
    },
  },
  {
    id: "t-yd-conversion-power",
    front: "Y↔Δ 변환 시 소비전력 변화?",
    back: "같은 선간전압에서 부하를 Y→Δ로 바꾸면 소비전력이 3배 증가.\n($\\Delta$ 결선이 상전압을 $\\sqrt{3}$배 더 받아 전력 3배)\n→ Y-Δ 기동: 기동 시 Y로 전류·토크 1/3.",
    subject: "전기이론",
    topic: "3상 교류",
    source: "preset",
    hint: "Δ 전력 = Y 전력의 3배",
    example: {
      question: "같은 전원에서 Y결선 시 소비전력이 3 kW일 때 Δ결선으로 바꾸면?",
      solution: [
        "$P_\\Delta = 3 \\times P_Y$",
        "$P_\\Delta = 3 \\times 3 = 9\\ \\text{kW}$",
      ],
      answer: "$P_\\Delta = 9\\ \\text{kW}$",
    },
  },
  {
    id: "t-3phase-impedance-current",
    front: "3상 Y부하의 상전류 계산?",
    back: "Y결선 상전류 $I_p = \\dfrac{V_p}{Z} = \\dfrac{V_L/\\sqrt{3}}{Z}$\nY에서는 선전류 = 상전류 ($I_L = I_p$).",
    subject: "전기이론",
    topic: "3상 교류",
    source: "preset",
    hint: "I_p = (V_L/√3) / Z",
    example: {
      question: "선간전압 380 V, 각 상 임피던스 $Z = 20\\ \\Omega$인 Y부하의 선전류는?",
      solution: [
        "$V_p = \\dfrac{V_L}{\\sqrt{3}} = \\dfrac{380}{1.732} \\approx 219.4\\ \\text{V}$",
        "$I_p = \\dfrac{V_p}{Z} = \\dfrac{219.4}{20} \\approx 10.97\\ \\text{A}$",
        "$I_L = I_p \\approx 11\\ \\text{A}$",
      ],
      answer: "$I_L \\approx 11\\ \\text{A}$",
    },
  },
  {
    id: "t-3phase-rotation",
    front: "3상 교류의 상순(상회전)?",
    back: "각 상이 120° 위상차를 두고 순서대로 변화.\n정상 상순 a-b-c (또는 R-S-T).\n상순이 바뀌면 3상 유도전동기는 역회전.",
    subject: "전기이론",
    topic: "3상 교류",
    source: "preset",
    hint: "두 상 바꾸면 역회전",
    example: {
      question: "3상 유도전동기의 회전 방향을 반대로 하려면?",
      solution: [
        "상순(상회전)을 반대로 만든다",
        "3상 중 임의의 두 상(전선)을 서로 바꿔 결선",
      ],
      answer: "3선 중 두 선을 서로 바꿔 연결",
    },
  },
  {
    id: "t-3phase-unbalanced",
    front: "불평형 3상과 대칭좌표법?",
    back: "불평형 3상은 정상분·역상분·영상분 3개 대칭 성분으로 분해.\n정상분: 정상 회전, 역상분: 반대 회전(제동·과열), 영상분: 동상(지락 검출).\n사고 해석의 기본 도구.",
    subject: "전기이론",
    topic: "3상 교류",
    source: "preset",
    hint: "정상·역상·영상 분해",
    example: {
      question: "3상 회로에서 1선 지락 사고 검출에 주로 이용되는 대칭 성분은?",
      solution: [
        "지락 시 세 상에 동상으로 나타나는 성분",
        "→ 영상분(zero-sequence)",
      ],
      answer: "영상분(영상 전류·전압)",
    },
  },
  {
    id: "t-3phase-line-current",
    front: "3상 부하의 선전류 계산 (전력 기준)?",
    back: "$I_L = \\dfrac{P}{\\sqrt{3}\\, V_L \\cos\\theta}$\n3상 유효전력 공식을 선전류로 정리한 형태.\n설비 용량·전선 굵기 산정에 사용.",
    subject: "전기이론",
    topic: "3상 교류",
    source: "preset",
    hint: "I_L = P / (√3 V_L cosθ)",
    example: {
      question: "선간전압 380 V, 유효전력 15 kW, 역률 0.8인 3상 부하의 선전류는?",
      solution: [
        "$I_L = \\dfrac{P}{\\sqrt{3}\\, V_L \\cos\\theta}$",
        "$I_L = \\dfrac{15000}{1.732 \\times 380 \\times 0.8}$",
        "$I_L \\approx \\dfrac{15000}{526.5} \\approx 28.5\\ \\text{A}$",
      ],
      answer: "$I_L \\approx 28.5\\ \\text{A}$",
    },
  },
  {
    id: "t-3phase-rotating-field",
    front: "3상 회전자계의 속도?",
    back: "3상 평형 전류가 만드는 합성 자계는 일정 크기로 회전.\n회전 속도 $N_s = \\dfrac{120 f}{P}$ [rpm]\n유도전동기·동기기 회전의 근본 원리.",
    subject: "전기이론",
    topic: "3상 교류",
    source: "preset",
    hint: "회전자계 = 동기속도로 회전",
    example: {
      question: "주파수 60 Hz, 6극인 경우 회전자계의 속도는?",
      solution: [
        "$N_s = \\dfrac{120 f}{P}$",
        "$N_s = \\dfrac{120 \\times 60}{6}$",
        "$N_s = 1200\\ \\text{rpm}$",
      ],
      answer: "$N_s = 1200\\ \\text{rpm}$",
    },
  },

  // ===== 비정현파 교류 (11) =====
  {
    id: "t-nonsinusoidal-rms",
    front: "비정현파의 실효값?",
    back: "각 고조파 실효값의 제곱합의 제곱근:\n$V = \\sqrt{V_0^2 + V_1^2 + V_2^2 + \\cdots}$\n$V_0$ 직류분, $V_1$ 기본파, $V_n$ n차 고조파 실효값.",
    subject: "전기이론",
    topic: "비정현파 교류",
    source: "preset",
    hint: "제곱합의 제곱근",
    example: {
      question: "기본파 100 V, 3고조파 40 V, 5고조파 30 V인 전압의 실효값은?",
      solution: [
        "$V = \\sqrt{100^2 + 40^2 + 30^2}$",
        "$V = \\sqrt{10000 + 1600 + 900}$",
        "$V = \\sqrt{12500} \\approx 111.8\\ \\text{V}$",
      ],
      answer: "$V \\approx 111.8\\ \\text{V}$",
    },
  },
  {
    id: "t-nonsinusoidal-power",
    front: "비정현파의 유효 전력?",
    back: "같은 차수의 전압·전류 성분끼리만 전력 발생:\n$P = V_0 I_0 + \\sum V_n I_n \\cos\\theta_n$\n다른 차수 간에는 평균 전력 0.",
    subject: "전기이론",
    topic: "비정현파 교류",
    source: "preset",
    hint: "같은 차수끼리만 전력",
    example: {
      question: "기본파 V=100, I=5, 위상차 0° / 3고조파 V=20, I=2, 위상차 0°인 비정현파 전력은?",
      solution: [
        "$P = V_1 I_1 \\cos\\theta_1 + V_3 I_3 \\cos\\theta_3$",
        "$P = 100 \\times 5 \\times 1 + 20 \\times 2 \\times 1$",
        "$P = 500 + 40 = 540\\ \\text{W}$",
      ],
      answer: "$P = 540\\ \\text{W}$",
    },
  },
  {
    id: "t-nonsinusoidal-power-factor",
    front: "비정현파 회로의 역률?",
    back: "$\\cos\\theta = \\dfrac{P}{V \\cdot I} = \\dfrac{\\text{유효전력}}{\\text{실효전압} \\times \\text{실효전류}}$\n고조파가 있으면 분모의 실효값이 커져 역률 저하.\n(왜형 역률 개념 포함)",
    subject: "전기이론",
    topic: "비정현파 교류",
    source: "preset",
    hint: "P / (V_rms · I_rms)",
    example: {
      question: "비정현파에서 유효전력 540 W, 실효전압 102 V, 실효전류 5.4 A일 때 역률은?",
      solution: [
        "$\\cos\\theta = \\dfrac{P}{V I}$",
        "$\\cos\\theta = \\dfrac{540}{102 \\times 5.4}$",
        "$\\cos\\theta \\approx \\dfrac{540}{550.8} \\approx 0.98$",
      ],
      answer: "역률 ≈ 0.98",
    },
  },
  {
    id: "t-harmonic-order-symmetry",
    front: "파형 대칭성과 포함 고조파?",
    back: "정현 대칭(반파 대칭): 짝수 고조파 없음 → 홀수 고조파만.\n우함수(여현 대칭): 사인항 없음.\n기함수(정현 대칭): 코사인항·직류분 없음.",
    subject: "전기이론",
    topic: "비정현파 교류",
    source: "preset",
    hint: "반파 대칭 → 홀수 고조파만",
    example: {
      question: "반파 대칭인 비정현파에 포함되지 않는 고조파는?",
      solution: [
        "반파 대칭 $f(t) = -f(t + T/2)$",
        "→ 짝수 고조파(2,4,6…)가 모두 0",
      ],
      answer: "짝수차 고조파 (2, 4, 6 …)",
    },
  },
  {
    id: "t-third-harmonic-3phase",
    front: "3상 회로에서 3고조파(영상분 고조파)?",
    back: "3의 배수 고조파(3,9,15…)는 세 상에서 동상 → 영상분처럼 행동.\nY결선 중성선에 합쳐져 흐르고, Δ결선 내부에서 순환.\n선간전압에는 3배수 고조파가 나타나지 않음.",
    subject: "전기이론",
    topic: "비정현파 교류",
    source: "preset",
    hint: "3배수 고조파 = 영상분 거동",
    example: {
      question: "3상 4선식에서 각 상 3고조파 전류가 5 A일 때 중성선 전류는? (3배수는 동상 합산)",
      solution: [
        "3배수 고조파는 세 상이 동상",
        "중성선 전류 = $3 \\times 5 = 15\\ \\text{A}$",
      ],
      answer: "약 15 A (3배수 고조파 합산)",
    },
  },
  {
    id: "t-nonsinusoidal-impedance",
    front: "고조파에 대한 회로의 임피던스 변화?",
    back: "n차 고조파에서:\n$X_{Ln} = n\\, \\omega L$ (n배 증가)\n$X_{Cn} = \\dfrac{1}{n\\,\\omega C}$ (1/n로 감소)\n→ 각 고조파마다 임피던스를 따로 계산해 합성.",
    subject: "전기이론",
    topic: "비정현파 교류",
    source: "preset",
    hint: "L은 n배, C는 1/n배",
    example: {
      question: "기본파에서 $X_L = 10\\ \\Omega$인 코일의 5고조파에 대한 리액턴스는?",
      solution: [
        "$X_{Ln} = n X_{L1}$",
        "$X_{L5} = 5 \\times 10 = 50\\ \\Omega$",
      ],
      answer: "$X_{L5} = 50\\ \\Omega$",
    },
  },
  {
    id: "t-fourier-coefficient",
    front: "푸리에 계수(직류분)의 의미?",
    back: "$a_0$는 1주기 평균값(직류분).\n$a_n,\\ b_n$은 n차 고조파의 코사인·사인 성분 크기.\nn차 고조파 진폭 $c_n = \\sqrt{a_n^2 + b_n^2}$.",
    subject: "전기이론",
    topic: "비정현파 교류",
    source: "preset",
    hint: "a₀ = 직류분(평균값)",
    example: {
      question: "어떤 n차 고조파의 $a_n = 3$, $b_n = 4$일 때 그 고조파의 진폭은?",
      solution: [
        "$c_n = \\sqrt{a_n^2 + b_n^2}$",
        "$c_n = \\sqrt{3^2 + 4^2} = \\sqrt{25} = 5$",
      ],
      answer: "진폭 = 5",
    },
  },
  {
    id: "t-harmonic-effects",
    front: "고조파가 전력 설비에 주는 악영향?",
    back: "변압기·전동기 과열(추가 손실), 콘덴서 과부하·공진, 중성선 과전류(3배수), 계전기 오동작, 통신선 유도장해.\n→ 필터·리액터로 억제.",
    subject: "전기이론",
    topic: "비정현파 교류",
    source: "preset",
    hint: "과열·공진·중성선 과전류",
    example: {
      question: "3상 4선식에서 3고조파가 특히 문제되는 곳은?",
      solution: [
        "3배수 고조파는 동상으로 중성선에 합산",
        "→ 중성선 과열·과전류",
      ],
      answer: "중성선 (과전류·과열)",
    },
  },
  {
    id: "t-distortion-power",
    front: "왜형(고조파) 무효전력 D?",
    back: "비정현파에서 피상전력 분해:\n$S^2 = P^2 + Q^2 + D^2$\n$P$ 유효, $Q$ 기본파 무효, $D$ 왜형(고조파) 전력.\n고조파가 없으면 $D = 0$.",
    subject: "전기이론",
    topic: "비정현파 교류",
    source: "preset",
    hint: "S² = P² + Q² + D²",
    example: {
      question: "$S = 1000\\ \\text{VA}$, $P = 800\\ \\text{W}$, $Q = 0$일 때 왜형전력 D는?",
      solution: [
        "$S^2 = P^2 + Q^2 + D^2$",
        "$D = \\sqrt{S^2 - P^2 - Q^2} = \\sqrt{1000^2 - 800^2}$",
        "$D = \\sqrt{360000} = 600$",
      ],
      answer: "$D = 600$ (왜형전력)",
    },
  },
  {
    id: "t-fundamental-frequency",
    front: "기본파와 고조파 주파수 관계?",
    back: "기본파 주파수 $f_1$에 대해 n차 고조파는 $f_n = n \\cdot f_1$.\n주기는 기본파와 같음 (모든 고조파가 한 기본 주기 안에 정수 개).",
    subject: "전기이론",
    topic: "비정현파 교류",
    source: "preset",
    hint: "n차 고조파 = n·기본 주파수",
    example: {
      question: "기본파 50 Hz일 때 7고조파의 주파수는?",
      solution: [
        "$f_n = n \\cdot f_1$",
        "$f_7 = 7 \\times 50 = 350\\ \\text{Hz}$",
      ],
      answer: "$f_7 = 350\\ \\text{Hz}$",
    },
  },
  {
    id: "t-rectangular-wave-harmonics",
    front: "구형파(방형파)의 고조파 구성?",
    back: "이상적 구형파는 기본파와 홀수 고조파(3,5,7…)만 포함.\n각 고조파 진폭은 $\\dfrac{1}{n}$에 비례 감소.\n짝수 고조파·직류분 없음(반파 대칭).",
    subject: "전기이론",
    topic: "비정현파 교류",
    source: "preset",
    hint: "구형파 = 홀수 고조파만",
    example: {
      question: "대칭 구형파에 포함되는 고조파 차수의 특징은?",
      solution: [
        "반파 대칭 → 짝수 고조파 0",
        "기본파 + 3,5,7… 홀수 고조파만",
      ],
      answer: "홀수차 고조파만 (1, 3, 5, 7 …)",
    },
  },

  // ===== 회로망 정리 (11) =====
  {
    id: "t-norton-theorem",
    front: "노턴의 정리?",
    back: "복잡한 능동 회로 → 한 개의 전류원 $I_N$ + 병렬 저항 $R_N$.\n$I_N$: 단자 단락전류, $R_N = R_{Th}$ (같은 등가저항).\n테브난과 상호 변환: $V_{Th} = I_N \\cdot R_N$.",
    subject: "전기이론",
    topic: "회로망 정리",
    source: "preset",
    hint: "전류원 + 병렬저항 (테브난 쌍대)",
    example: {
      question: "$V_{Th} = 12\\ \\text{V}$, $R_{Th} = 4\\ \\Omega$인 테브난 회로의 노턴 등가는?",
      solution: [
        "$R_N = R_{Th} = 4\\ \\Omega$",
        "$I_N = \\dfrac{V_{Th}}{R_{Th}} = \\dfrac{12}{4} = 3\\ \\text{A}$",
      ],
      answer: "$I_N = 3\\ \\text{A},\\ R_N = 4\\ \\Omega$",
    },
  },
  {
    id: "t-mesh-analysis",
    front: "망 해석법(메시 전류법)?",
    back: "각 폐로에 가상 망전류를 설정하고 KVL을 적용해 연립방정식.\n미지수 = 독립 폐로 수.\n공통 가지에는 인접 망전류의 차가 흐름.",
    subject: "전기이론",
    topic: "회로망 정리",
    source: "preset",
    hint: "폐로마다 KVL 연립",
    example: {
      question: "독립 폐로가 3개인 회로를 망 해석할 때 세워야 할 방정식 수는?",
      solution: [
        "망전류 미지수 = 독립 폐로 수",
        "독립 폐로 3개 → 방정식 3개",
      ],
      answer: "3개 (독립 폐로 수만큼)",
    },
  },
  {
    id: "t-node-analysis",
    front: "절점 해석법(노드 전압법)?",
    back: "기준 절점을 정하고 나머지 절점 전압을 미지수로 KCL 적용.\n미지수 = (전체 절점 수 − 1).\n전류원이 많은 회로에 유리.",
    subject: "전기이론",
    topic: "회로망 정리",
    source: "preset",
    hint: "절점마다 KCL, 미지수 = 절점-1",
    example: {
      question: "절점이 총 4개인 회로를 절점 해석할 때 미지 전압의 개수는?",
      solution: [
        "기준 절점 1개 선택",
        "미지수 = 절점 수 − 1 = 4 − 1",
      ],
      answer: "3개",
    },
  },
  {
    id: "t-millman-theorem",
    front: "밀만의 정리?",
    back: "여러 전압원이 병렬일 때 공통 단자 전압:\n$V = \\dfrac{\\sum (E_k / R_k)}{\\sum (1 / R_k)} = \\dfrac{\\sum E_k G_k}{\\sum G_k}$\n병렬 전원 회로를 한 번에 계산.",
    subject: "전기이론",
    topic: "회로망 정리",
    source: "preset",
    hint: "병렬 전압원 합성 공식",
    example: {
      question: "$E_1 = 10\\ \\text{V}(R_1=2\\ \\Omega)$, $E_2 = 4\\ \\text{V}(R_2=2\\ \\Omega)$ 병렬 시 공통 전압은?",
      solution: [
        "$V = \\dfrac{E_1/R_1 + E_2/R_2}{1/R_1 + 1/R_2}$",
        "$V = \\dfrac{10/2 + 4/2}{1/2 + 1/2} = \\dfrac{5 + 2}{1}$",
        "$V = 7\\ \\text{V}$",
      ],
      answer: "$V = 7\\ \\text{V}$",
    },
  },
  {
    id: "t-reciprocity-theorem",
    front: "가역 정리(상반 정리)?",
    back: "선형 수동 회로에서 한 가지에 넣은 전원과 다른 가지의 응답을 서로 바꿔도 비(比)는 동일.\n전원 위치와 측정 위치를 맞바꿔도 전류·전압 응답이 같음.",
    subject: "전기이론",
    topic: "회로망 정리",
    source: "preset",
    hint: "전원·응답 위치 교환해도 동일",
    example: {
      question: "선형 회로에서 A에 1 V를 넣으니 B에 0.2 A가 흘렀다. 같은 1 V를 B에 넣으면 A에 흐르는 전류는?",
      solution: [
        "가역 정리: 전원·응답 위치를 바꿔도 응답 동일",
        "→ A에 0.2 A",
      ],
      answer: "0.2 A (가역 정리)",
    },
  },
  {
    id: "t-source-transformation",
    front: "전원 변환(등가 전원)?",
    back: "전압원 $E$ + 직렬 $R$ ↔ 전류원 $I = \\dfrac{E}{R}$ + 병렬 $R$ (저항 동일).\n회로 단순화·해석 편의를 위해 자유롭게 변환.",
    subject: "전기이론",
    topic: "회로망 정리",
    source: "preset",
    hint: "I = E/R, 저항은 그대로",
    example: {
      question: "기전력 20 V, 직렬저항 $5\\ \\Omega$ 전압원을 전류원으로 변환하면?",
      solution: [
        "$I = \\dfrac{E}{R} = \\dfrac{20}{5} = 4\\ \\text{A}$",
        "병렬 저항 = 그대로 $5\\ \\Omega$",
      ],
      answer: "전류원 4 A + 병렬 5 Ω",
    },
  },
  {
    id: "t-delta-wye-conversion",
    front: "Δ→Y 변환 공식?",
    back: "$R_a = \\dfrac{R_{ab}\\, R_{ca}}{R_{ab} + R_{bc} + R_{ca}}$\n분자: 그 절점에 모인 두 Δ저항의 곱, 분모: 세 Δ저항의 합.\n등저항이면 $R_Y = \\dfrac{R_\\Delta}{3}$.",
    subject: "전기이론",
    topic: "회로망 정리",
    source: "preset",
    hint: "Δ→Y: 곱 / 합, R_Y = R_Δ/3",
    example: {
      question: "Δ 결선 각 변이 모두 $9\\ \\Omega$일 때 등가 Y 결선 각 변 저항은?",
      solution: [
        "등저항 변환: $R_Y = \\dfrac{R_\\Delta}{3}$",
        "$R_Y = \\dfrac{9}{3} = 3\\ \\Omega$",
      ],
      answer: "$R_Y = 3\\ \\Omega$",
    },
  },
  {
    id: "t-max-power-transfer-efficiency",
    front: "최대 전력 전달 시 효율?",
    back: "$R_L = R_{Th}$로 최대 전력 전달할 때, 내부 저항에서도 같은 전력 소비.\n→ 전달 효율은 50 %.\n(통신·신호용은 정합, 전력 전송용은 효율 우선이라 정합 안 함)",
    subject: "전기이론",
    topic: "회로망 정리",
    source: "preset",
    hint: "정합 시 효율은 딱 50%",
    example: {
      question: "$R_L = R_{Th}$로 최대 전력을 전달할 때 전원에서 부하로 가는 효율은?",
      solution: [
        "부하 소비 = 내부저항 소비 (둘 다 같음)",
        "$\\eta = \\dfrac{P_L}{P_{total}} = \\dfrac{1}{2}$",
      ],
      answer: "50 %",
    },
  },
  {
    id: "t-compensation-theorem",
    front: "보상 정리?",
    back: "회로의 한 소자값이 $\\Delta Z$만큼 변하면, 그 변화는 변화 가지에 등가 보상 전원($-\\Delta Z \\cdot I$)을 삽입한 것과 같다.\n소자 변화에 따른 회로 변화량 계산에 사용.",
    subject: "전기이론",
    topic: "회로망 정리",
    source: "preset",
    hint: "소자 변화 → 등가 보상 전원",
    example: {
      question: "어떤 가지의 저항이 변했을 때 회로 응답 변화를 구하는 데 쓰이는 정리는?",
      solution: [
        "소자값 변화 효과를 보상 전원으로 치환",
        "→ 보상 정리(Compensation theorem)",
      ],
      answer: "보상 정리",
    },
  },
  {
    id: "t-thevenin-with-load",
    front: "테브난 등가로 부하 전류 구하기?",
    back: "부하 $R_L$의 전류 $I_L = \\dfrac{V_{Th}}{R_{Th} + R_L}$\n부하가 바뀌어도 $V_{Th}$, $R_{Th}$는 그대로라 재계산이 쉬움.",
    subject: "전기이론",
    topic: "회로망 정리",
    source: "preset",
    hint: "부하 전류 = V_Th /(R_Th+R_L)",
    example: {
      question: "$V_{Th} = 18\\ \\text{V}$, $R_{Th} = 3\\ \\Omega$일 때 $R_L = 6\\ \\Omega$에 흐르는 전류는?",
      solution: [
        "$I_L = \\dfrac{V_{Th}}{R_{Th} + R_L}$",
        "$I_L = \\dfrac{18}{3 + 6} = \\dfrac{18}{9}$",
        "$I_L = 2\\ \\text{A}$",
      ],
      answer: "$I_L = 2\\ \\text{A}$",
    },
  },
  {
    id: "t-superposition-power-caution",
    front: "중첩의 원리 적용 시 주의점?",
    back: "전류·전압은 각 전원 응답을 대수합 가능.\n그러나 전력($P = I^2 R$)은 전류의 제곱이라 비선형 → 중첩 불가.\n전력은 합성 후의 전류·전압으로 따로 계산해야 함.",
    subject: "전기이론",
    topic: "회로망 정리",
    source: "preset",
    hint: "전력은 중첩 불가(제곱 항)",
    example: {
      question: "어떤 저항에 전원 A 단독 시 2 A, 전원 B 단독 시 3 A가 흐른다(같은 방향). 두 전원 동시일 때 그 저항(1 Ω)의 소비전력은?",
      solution: [
        "전류는 중첩: $I = 2 + 3 = 5\\ \\text{A}$",
        "전력은 합성 전류로 계산: $P = I^2 R = 5^2 \\times 1$",
        "$P = 25\\ \\text{W}$ (전력 따로 합산 금지)",
      ],
      answer: "$P = 25\\ \\text{W}$",
    },
  },
];
